### ISSUE TITLE
Add non GAE memcache functionality.

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#1059]
AbsAuthServlet references GAE Memcache and runtime fails when invoked.

**Comment by Meera-Remadevi** [comment]
Hi,
We have been working on a clone of draw.io integrated to our google drive working from a server. It was an old version [v12.1.7]. We recently pulled and merged the v13.4.5 of draw.io. After that the google drive authentication is failing. The error message and related info is posted in [stack overflow](https://stackoverflow.com/questions/63018997/my-clone-of-draw-io-fails-doget-when-authenticating-to-google-drive) . The error message says it has do with the AbsAuthServlet.java file. As suggested in StackOverflow,  I am hoping its the same bug causing the issue. A fix for this would be great. I am new to this and any suggestions or advice on the matter will be a huge help. Thankyou !

**Comment by Meera-Remadevi** [comment]
Hi
Is there a work around or a previous working version of draw.io that we can use while we wait for this issue to be fixed??

**Comment by davidjgraph** [comment]
There is no known workaround.

**Comment by seanhalle** [comment]
Hello, I am also interested in bringing up Draw.io on our company's own servers.  When do you think a fix will be available?

**Comment by davidjgraph** [comment]
Please try the latest build to see what the current state is.

**Comment by Meera-Remadevi** [comment]
Hi, I tried the latest build. still getting the same error.[ Kindly note, I had conflicts in mxclient.js and .min files that I ignored. Not sure, if that could be an issue.  The mxclient.js version we are using is 4.2 from here [https://github.com/jgraph/mxgraph/blob/master/javascript/mxClient.js]]

**Comment by davidjgraph** [comment]
What's the exception you get?

**Comment by Meera-Remadevi** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by davidjgraph** [comment]
That means there's an exception causing https://github.com/jgraph/drawio/blob/master/src/main/java/com/mxgraph/online/AbsAuthServlet.java#L251 to catch. What is causing that exception when you debug?

**Comment by Meera-Remadevi** [comment]
```HTTP Status 500 - Can't make API call memcache.Set in a thread that is neither the original request thread nor a thread created by ThreadManager
type Exception report

message Can't make API call memcache.Set in a thread that is neither the original request thread nor a thread created by ThreadManager

description The server encountered an internal error that prevented it from fulfilling this request.

exception

com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call memcache.Set in a thread that is neither the original request thread nor a thread created by ThreadManager
	com.google.apphosting.api.ApiProxy$CallNotFoundException.foreignThread(ApiProxy.java:800)
	com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:175)
	com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:172)
	com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	com.google.appengine.api.memcache.MemcacheServiceImpl.quietGet(MemcacheServiceImpl.java:26)
	com.google.appengine.api.memcache.MemcacheServiceImpl.put(MemcacheServiceImpl.java:69)
	com.google.appengine.api.memcache.stdimpl.GCache.put(GCache.java:157)
	com.mxgraph.online.AbsAuthServlet.putCacheValue(Unknown Source)
	com.mxgraph.online.AbsAuthServlet.doGet(Unknown Source)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.32 (Ubuntu) logs.
```

**Comment by Meera-Remadevi** [comment]
This is what I get from console logs.

**Comment by davidjgraph** [comment]
That's the correct part, thanks. Please pull master and let me know if that improves it.

**Comment by Meera-Remadevi** [comment]
Hi, 
I pulled the latest changes to our clone[ with our custom changes] and deployed. No change in exception.
I tried taking a pristine clone of draw.io, added our clientID and secret along with modifications in host name and additions in preconfig.js. After build and deploy to server, again i get the login attempt  failed error but this time there are 2 exceptions: 500 internal server error and 404 exception: requested resource not available.
```
HTTP Status 404 -
type Status report

message

description The requested resource is not available.

Apache Tomcat/8.0.32 (Ubuntu)
```

**Comment by davidjgraph** [comment]
For the clean build, how are you building it?

**Comment by Meera-Remadevi** [comment]
Cd etc/build
Ant war

**Comment by Meera-Remadevi** [comment]
hi 
i did an ant clean and build it again. now i get the same error as that of pristine draw.io deployed from our server.
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/draw/google?getState=1:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
```
HTTP Status 404 -
type Status report

message

description The requested resource is not available.

Apache Tomcat/8.0.32 (Ubuntu)
```

**Comment by Meera-Remadevi** [comment]
The memcache issue seems to be resolved. Thank you for the help.

**Comment by jyothiyellapu8** [comment]
hi
can you please let me know how the memcache issue is resolved? Thank you for your help in advance!

**Comment by Meera-Remadevi** [comment]
Hi,

**Comment by jyothiyellapu8** [comment]
thank you for your reply
I pulled the latest changes but still getting memcache error like this
Type Exception Report

Message Can't make API call memcache.Set in a thread that is neither the original request thread nor a thread created by ThreadManager

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call memcache.Set in a thread that is neither the original request thread nor a thread created by ThreadManager
	com.google.apphosting.api.ApiProxy$CallNotFoundException.foreignThread(ApiProxy.java:800)
	com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:175)
	com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:172)
	com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	com.google.appengine.api.memcache.MemcacheServiceImpl.quietGet(MemcacheServiceImpl.java:26)
	com.google.appengine.api.memcache.MemcacheServiceImpl.put(MemcacheServiceImpl.java:69)
	com.google.appengine.api.memcache.stdimpl.GCache.put(GCache.java:157)
	com.mxgraph.online.AbsAuthServlet.doGet(Unknown Source)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

**Comment by ashrafteleb** [comment]
It looks like you are using an old version of the code. Please update and clean. Let us know if that didn't fix the issue

**Comment by jyothiyellapu8** [comment]
Hi

**Comment by jyothiyellapu8** [comment]
Hi

**Comment by jyothiyellapu8** [comment]
Hi
Thank you for your quick response
I pulled the latest code and merge my custom code changes but still getting same error in my console log
Type Exception Report

Message Can't make API call memcache.Set in a thread that is neither the original request thread nor a thread created by ThreadManager

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call memcache.Set in a thread that is neither the original request thread nor a thread created by ThreadManager
com.google.apphosting.api.ApiProxy$CallNotFoundException.foreignThread(ApiProxy.java:800)
com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:175)
com.google.apphosting.api.ApiProxy$1.get(ApiProxy.java:172)
com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
com.google.appengine.api.memcache.MemcacheServiceImpl.quietGet(MemcacheServiceImpl.java:26)
com.google.appengine.api.memcache.MemcacheServiceImpl.put(MemcacheServiceImpl.java:69)
com.google.appengine.api.memcache.stdimpl.GCache.put(GCache.java:157)
com.mxgraph.online.AbsAuthServlet.doGet(Unknown Source)
javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

**Comment by ashrafteleb** [comment]
There should be no reference to com.google.appengine.api.memcache. Please check AbsAuthServlet code
Also, we cannot give help to custom code changes. Does the original unchanged code work?
