### ISSUE TITLE
Please support OneDrive App Folder

### ISSUE THREAD

**Issue by m8d3** [jgraph/drawio#1217]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
draw.io requires full access to all folders on OneDrive. 

**Describe the solution you'd like**
Please Support OneDrive App Folder for personal OneDrive accounts as described here:
https://stackoverflow.com/a/48951794
This does not need full access to onedrive, but only to Files.ReadWrite.AppFolder delegated permission.

**Comment by davidjgraph** [comment]
If you use the app folder, you cannot share with other users. That's the tradeoff between full OneDrive and app folder.

Dropbox don't really allow full access, so we went with app folder only, losing sharing on Dropbox. The usage on Dropbox is minimal, probably heavily because there is no sharing.

So yes, full access annoys some people, but we think lack of sharing will annoy more.

**Comment by m8d3** [comment]
Many thanks for the clarification.
