### ISSUE TITLE
Can't delete shape in old diagram

### ISSUE THREAD

**Issue by kid2709** [jgraph/drawio#1224]
Dear all, I have one problem can't fix
My old diagram can't delete the shape, but another diagram can't delete. I don't know why. So if someones can fix this problem, pls tell me how can do it.
Thank for your time to see!

**Comment by mararad** [comment]
Hi,

could you tell me please:
* diagrams.net version you are using, please? Can be seen under Help
* steps you performed in order to delete a shape
* if you repeat all the steps in other browsers and Incognito mode, does it help?
* check if a layer with a shape in question is locked

If nothing helps, could you attach a video and draw.io file so I could test it directly (and tell me the exact shape I should try to delete)

Thanks,
