### ISSUE TITLE
Dashed Underline

### ISSUE THREAD

**Issue by gurjeetsingh** [jgraph/drawio#1229]
* [ y] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [y ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
In many CS courses, Entity Relationship Diagrams (ERD) are made at the beginning of database courses. 
In these ERD diagrams, weak entity sets with partial keys require the attributes that are part of the partial key to be underlined with a dashed line. As this is common across many Computer Science programs, it may be a worthy pursuit to resolve.

**Describe the solution you'd like**
An option to alter the underline of text (as if it were a line). Or a weak entity set attribute shape templet/preset.

**Describe alternatives you've considered**
Drawing and placing the line, although consistency is difficult.

**Additional context**
N/A

**Comment by mararad** [comment]
Hi,

at the moment it is not possible to do that in UI, but you could try the following in order to insert a dashed underline:

click </> button in the toolbar and add e.g. 

<div style="border-bottom: 1px dashed black">Test</div>

If this is not what you are looking for, feel free to attach an example.
