### ISSUE TITLE
Add groups for layers

### ISSUE THREAD

**Issue by helplessheadless** [jgraph/drawio#1231]
I really miss the ability to put the layers in groups and subgroups like in Gimp. It would be a big improvement for usabillity of greater diagrams. 

I hope this post fits the way he is made.

**Comment by mararad** [comment]
Support grouped layers manipulation
"I was wanting to make a custom property for certain layers then use custom linking to hide a group of layers at a time instead of having to input each id. Any plans to implement layer grouping and the ability to manipulate grouped layers like we can with single layers using custom links?"

https://desk.draw.io/a/tickets/13144
