### ISSUE TITLE
Line jumps for curved edges

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1385]

**Comment by firedrow** [comment]
This was supposedly a [released feature](https://drawio-app.com/draw-io-now-supports-line-jumps/) in 2017, was it removed?

**Comment by davidjgraph** [comment]
That's line jumps for orthogonal edges, this is for curved.

**Comment by firedrow** [comment]
> 
> 
> That's line jumps for orthogonal edges, this is for curved.

Sorry, I missed the distinction as curved.  Is this still a feature though?  In 13.9.9 I don't have Line Jump property for Orthogonal.

**Comment by mararad** [comment]
Hi,

When you add a line jump, just make sure that the line is "in front"
i.e select the line you want to have line jumps and click Arrange - To front.
​
Does this help?

Regards,

**Comment by firedrow** [comment]
That doesn't modify the crossed lines to show and arc or some other
indicator of crossed/non-connected lines.

Dustin

**Comment by Krinkle** [comment]
Bump

**Comment by Krinkle** [comment]
When I change a line type from Sharp or Rounded to Curved, the "Lime jumps" option dissappears. I believe this issue is a feature request for that.

Here's what that looks like today, with an example of where I'd like to use it:

<img height="200" alt="Screenshot Sharp" src="https://user-images.githubusercontent.com/156867/191798979-7ec01cc1-f87b-4c8c-a451-cc029acba7c8.png">
<img height="120" alt="Screenshot" src="https://user-images.githubusercontent.com/156867/191798986-e5cc1a5b-70dd-41ab-837c-8bc0298f6dfb.png">
