### ISSUE TITLE
Exported pdf contains obsolete "ProcSets" entry

### ISSUE THREAD

**Issue by drevicko** [jgraph/drawio#1483]
### Preflight Checklist

* [x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When a diagram is exported as pdf and used included in a latex file (compiled by `pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)`), an warning complaining about the ProcSets entry that isn't a dict. [This TeX stack exchange question](https://tex.stackexchange.com/questions/154919/pdflatex-warning-pdf-inclusion-invalid-other-resource-which-is-no-dict-ign) discusses the issue and claims that ProcSets is obsolete.

**To Reproduce**
1. Export a diagram to pdf
2. Import it into a tex document
3. Compile with pdflatex

**Expected behavior**
No warnings are generated concerning the exported pdf.

**draw.io version (In the Help->About menu of the draw.io editor):**

- 13.9.2

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 86.0.4240.193 (Official Build) (x86_64)

**Additional context**
This relates to obsolete metadata in exported pdfs.

**Comment by MakisH** [comment]
I had the same issue, but seems to be fixed in recent versions of drawio. I simply opened my graphs again (in v15.3.3), exported again, and it looks like the PDF standard is much more recent now.

Disclaimer for people landing here for the same reason: This can still make pdflatex throw another warning:
```
pdfTeX warning: pdflatex (file <name>.pdf): PDF inclusion: found PDF 
version <1.7>, but at most version <1.5> allowed
```
The next page you want to read is https://tex.stackexchange.com/questions/52317/pdftex-warning-version-allowed. Good luck!
