### ISSUE TITLE
Embedded SVG data doesn't render in image export

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1506]
Embedding and SVG in a diagram and exporting to raster, the SVGs don't appear.
This most likely also affects PDF export.

**Comment by ati-mu** [comment]
This issue prevents users from creating nice vector graphics using imported SVGs. The imported SVGs are embedded into the exported SVG as raster images, and they look horrible. Most viewers and browsers do not even display these embedded raster images, so there are only empty spaces instead of images. Please, fix this.

**Comment by alderg** [comment]
This works for me. We'd need the exact steps to reproduce the problem.
