### ISSUE TITLE
Cant connect to bottom of UML class

### ISSUE THREAD

**Issue by wolf99** [jgraph/drawio#154]
- Add 2 UML classes to the worksheet 
- Add an Composition1 arrow
- Attempt to have arrow join bottom of one class to top of next class.

Cannot do this, the arrow keeps trying to connect to the sides of the last class field item instead.

**Comment by alderg** [comment]
Try connect to the title of the class.

**Comment by wolf99** [comment]
@alderg 
This is not really a usable solution! When one is making class diagrams the usual way is for relations to connect at least one end to the sides or bottom of the base or parent class, for example to show derivation of a class when classes need to be arranged vertically. Like so:

![1](https://user-images.githubusercontent.com/281700/30052848-dac4d398-921e-11e7-95bf-f0c10f1b8939.PNG)

Whereas your suggestion results in the following:

![2](https://user-images.githubusercontent.com/281700/30052881-eaee4862-921e-11e7-9044-ca4d4c5d97fb.PNG)

Which is not a very useful solution...

**Comment by alderg** [comment]
Connect to the title of the class with a blue highlight, not to a anchor point or with a green highlight (blue highlight will float around the class).

**Comment by wolf99** [comment]
@alderg Ah! Thank you! Didn't see that there were different colour highlights showing if I moved the cursor slightly :)

**Comment by pmitmc** [comment]
In case it helps someone - sometimes this is not ideal, because multiple line relationships end up overlapped. 
I found a workaround by right-clicking on the last member of the class, and locking it. Then, the anchor points that show up when you drag a connector's end over the class are the ones of the class itself, and you can choose where to anchor.

![Image](https://github.com/user-attachments/assets/df8f0be7-890f-4ef0-885e-764c9553f7c0)

![Image](https://github.com/user-attachments/assets/de46221f-a4ad-48c3-8ba0-851455d4f7c2)
