### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1547]
Every object having a note, so that I can write a few more words there just for the memory.

Tooltips is useful for a simple note but it loses value when you have any complexity to share. A notes field with Markdown support, or Markdown support in the tooltips would be useful.

**Comment by drewburlingame** [comment]
I need the Markdown support.

Using tooltips to display additional info to viewers of the diagram is not very useful because the information has to be broken into different page properties which loses some value.  And since the properties are sorted alphabetically instead of in the order specified, the info appears out of order.  Adding numbers just to sort them is also counter productive because the numbers mean nothing to the user.

I would like to be able to be able to provide users a more useful depiction of the metadata for a given vertex or edge.

**Comment by drewburlingame** [comment]
A similar topic #711  was closed by the stale bot 20 days ago.

**Comment by ericawilson9** [comment]
Honestly, LOVE how agile this is...not being able to attach a note to an object the only reason I would consider an alternative. Seems like a must have!?

**Comment by boscorp** [comment]
I also support this feature, it's a must

**Comment by davidjgraph** [comment]
To vote for the issue thumbs up the original post. Please do not "me too", "+1", it pollutes useful comments in the thread.

**Comment by davidjgraph** [comment]
I think this is about the markdown support, rather than notes itself. It's also about people not discovering the edit data function to produce a tooltip on hover.

I'm going to close this one and re-open markdown support #711 . If you have a specific case, not related to wanting markdown, please add to this thread.

**Comment by ericawilson9** [comment]
And, that’s why I don’t use draw anymore…

_
eric wilson | whaletap.com

**Comment by I2rys** [comment]
I was wondering in when this feature will be implemented because It's really useful & needed and It would be useful If It has a switch where you can switch to markdown and normal text(Like notepad).
