### ISSUE TITLE
Bulk Import/ export with data in CSV, Excel ...formats

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1604]
Import/export data in CSV and/or Excel formats. It will help in adjusting the data as well as bulk operations.

"CSV export useful for integration with other text pipelines"

"Ability to export json/csv from an existing diagram would speed up my ability to create a diagram/model of what I want to see conceptually, to easily generate the csv format and options I want - and then move on to my data process to generate in the right csv format to get the final diagram I want to generate "

**Comment by GabeGiro** [comment]
@davidjgraph may I ask why is this feature declined? 

This https://www.drawio.com/blog/import-lucidchart-edu refers to a [Chrome extension](https://chromewebstore.google.com/detail/diagramsnet-and-drawio-im/cnoplimhpndhhhnmoigbanpjeghjpohi) that's out-of-date and can't install due to `This extension is no longer available because it doesn't follow best practices for Chrome extensions.`  

So there is no way to import LucidChart flows. And one of the export options in LucidChart is CSV

**Comment by davidjgraph** [comment]
Lucidchart to csv to draw.io wouldn't work. Try it.

If you want to import Lucid, select all, copy, paste into draw.io.
