### ISSUE TITLE
Hover change on shapes with links

### ISSUE THREAD

**Issue by czarekplpl** [jgraph/drawio#1633]
Hello.
Are any button visual effects available in Drawio, such as hover color change when pointed, etc...
If yes, can I have the link to the documentation?
Rgds
Wesley.

**Comment by mararad** [comment]
Hi, it not possible at the moment. 

Regards,

**Comment by mararad** [comment]
https://trello.com/c/tUgC4mWz/302-change-behaviour-of-mouseover-hover-over-an-element-with-a-hyperlink
merged wih this issue

David Benson "I have made some drawings (mostly buttons with a text) and I have added http links to desired pages within confluence. Works flawlessly. The only drawback for me is that the mouseover effect on that button is not really "jumping" at the viewer. The button is just outlines with a blue frame, indicating to the viewer that this is a clickable button within the drawing.

I would like to change the behaviour of a link when hovering the mouse over it. (Like at least changing the color to something more visible or, preferably, having the possibility to change the color of the button itself.) Example: My button is a rectangular shape with a light orange color containing "GOTO Page 2" as text. I add a hyperlink and publish that.
The effect I now would like to have is to have the button change its colour when the viewer points at it so that he can more easily see that this will ... "trigger" something."

**Comment by davidjgraph** [comment]
Closing through lack of additional interest.

**Comment by mararad** [comment]
Re-open (asked here: https://webapps.stackexchange.com/questions/167164/diagrams-net-draw-io-modifying-the-mouse-over-hover-style-for-a-shape-with-link)

**Comment by chendy** [comment]
Yes, I'm interested in this : )

**Comment by lricci** [comment]
Yes, I'm really interested in this feature !

**Comment by jmtemmos** [comment]
I vote for this feature

**Comment by FHaslwanter** [comment]
Would be great!
