### ISSUE TITLE
Wrong Font on Pdf-Export for Asciimath

### ISSUE THREAD

**Issue by Zomono** [jgraph/drawio#170]
When you do a pdf-export for the attached file you may recognize the different font that is used within the exported pdf file. 

Example xml:
[Bug-Pdf-Export-Asciimath.xml.zip](https://github.com/jgraph/drawio/files/1451613/Bug-Pdf-Export-Asciimath.xml.zip)

Expected:
![expected](https://user-images.githubusercontent.com/8547034/32517450-cd4cf80c-c406-11e7-8251-785ac507ff10.png)
Actually:
![actually](https://user-images.githubusercontent.com/8547034/32517455-cea50140-c406-11e7-9607-932ecd9d60e0.png)

The reason is maybe a missing font on the export server. Maybe one of the fonts listed here [https://github.com/Khan/KaTeX/tree/master/static/fonts](KaTeX-Fonts)

It would be nice if the desktop-app of draw.io does the export locally on my machine, because then I am able to decide which fonts are installed and thus are able to solve such problems on my own.

Thank you for such a great app so far.

**Comment by davidjgraph** [comment]
The desktop app now performs the PDF export locally, so the font from the OS will be used. In the online version you can use Print to PDF as a workaround.

We would need to install custom fonts on the image export servers to make this work everywhere, that doesn't scale in terms of number of fonts and number of server (we can't image them because they are Macs).
