### ISSUE TITLE
Add/move/delete ports on SysML blocks

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1704]
I would like to use SysML blocks with a certain number of in, out and bi-directional port nodes. The predefined "Transmission" block provides one of each. But how can I move the ports, add ports or delete ports?

https://desk.draw.io/a/tickets/34845

**Comment by davidsh-dev** [comment]
It's an essential feature. How it is not possible to add ports is beyond me.

**Comment by alderg** [comment]
See https://www.diagrams.net/doc/faq/shape-connection-points-customise

**Comment by SebCanet** [comment]
Hi,
I think it's not completed because it's not the same problem. What you are linking as duplicate is about contact point, to link boxes, the problem is the shape of the box.
What we need is add or delete ports on this kind of blocks:
![image](https://user-images.githubusercontent.com/6362199/171288187-bc33a41e-37f6-4e0a-a566-3e57654da59f.png)
Also change the port direction, the arrow and also the <> one.

**Comment by SebCanet** [comment]
Hi,
do you have any progress for this feature?
Thanks.

**Comment by davidjgraph** [comment]
No, otherwise we'd have posted that there was progress.
