### ISSUE TITLE
Copy-paste objects in multiple layers

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1759]
"For several reasons I need to use layers in my drawing. But if I copy and paste set of objects from different layers, they're all pasted into active layer only."

"Without copy paste working with layers, layers are unusable in most larger working situations where you share diagrams. Why so?

Cannot create templates with layer information, as once you copy any group of objects with layer information stored, that layer information is lost.
Cannot even build on other diagrams with layer information, since as soon as I copy paste even one single object (which is rare, you would typically start by copying atleast a part of an existing diagram with many objects), the layer setting is overwritten with the layer I happen to currently have selected, for all objects.
Why this comment? I think that the description of this card does not communicate the impact of this behavior - that it in facts makes layers unusable in any larger work setting where diagrams are shared.

One workaround could be to copy the entire diagram file and remove what you do not need, but you would still have to manually set the layer info for any new objects that you add, since copy paste cannot be used. You cannot copy groups that have the elements on different layers. Cumbersome at best."

David "Plus the copy only copies the current layer"

**Comment by mawid6** [comment]
### Layer information is lost when doing Copy-Paste

(_I am the original poster of this issue_) The above is **a better title**. 
IMO - **Layers are partly, but significantly broken**, since: 

Layer data is not retained when copy pasting objects.

But! There is **a decent workaround**:

### Use tags!

Tags are stored with the objects and are not lost during a copy-paste operation, and they are also captured if the shapes are added to a custom shapelibrary!

To get the toggling (similar to the floating layers toolbar), you add toggle buttons with actions, like described here: 
https://drawio-app.com/interactive-diagrams-with-custom-links-and-actions/

Its a bit of work, but even the toggles you set up can be grouped as one shape and reused, either via copy paste (works great) and/or in a shapes library.

Tags work as expected!

Additionally, look at the hidden tags plugin, for instance, for quick tagging of alot of shapes in a diagram.

BR! /m

**Comment by mawid6** [comment]
Image link is broken, here is a new upload:

![drawio layers bug](https://user-images.githubusercontent.com/77722885/108505546-dc90f080-72b7-11eb-9376-a1fe6be394a4.gif)

**Comment by chipbite** [comment]
Tags is now getting a UI that is similar to layers (see #1240), which makes using tags very similar to using layers - and the tags metadata is part of each object so it is not lost when doing copy paste. Works great, and currently has more flexibility than using layers.

https://www.diagrams.net/blog/tags-in-diagrams
