### ISSUE TITLE
Update Hydraulic Valves stencils

### ISSUE THREAD

**Issue by egrimate** [jgraph/drawio#1762]
https://images.app.goo.gl/QvxBjFuMxub4CULJ9
https://images.app.goo.gl/NSv58fngdMhFLi4i9

Original discussion:
https://groups.google.com/g/drawio/c/tRLnVzTDRFs

**Comment by PVC-C** [comment]
The Pictures from the Post here aren’t available anymore, but you have a Bunch of Valves now that are pretty helpful.
The Problem is, that they are centered on the whole Symbol and not on the Flow Part.
The Handle or Motor in the Symbol move the Center for Connections to the Side and it looks very unprofessional.
