### ISSUE TITLE
issues saving local file or google drive file

### ISSUE THREAD

**Issue by mfaisalk1** [jgraph/drawio#1827]
I am constantly getting this error message in web app. kindly advice

"An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk."

### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.6.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mararad** [comment]
Hi,

Are you sure you are using 12.6.7 online version? My suggestion would be to use a workaround to save the file https://desk.draw.io/support/solutions/articles/16000089553-manually-save-your-diagram-when-standard-saving-fails

When you save it, check the version under Help. If it is not 14.4.0, close all tabs, load https://app.diagrams.net/clear.html and then load diagrams.net again. Then open the file and check if you can save it.

If you have the same save error with the latest version,, attach a print screen of a whole browser when the error appears please and tell me what steps exactly you performed in order to save the file

Thanks,

**Comment by mfaisalk1** [comment]
yes, I could simulate the issue once again for you.

This only happens, if I import it into powerpoint using Addin. I am using powerpoint 2016

if I dont import the file, there is no issue of working on the diagrams in web app.

Here I recorded the complete  video for you to show the problem in more detail and also the version of the diagrams.net

https://share.clickup.com/clip/p/t3667419/f1b9d751-9313-4490-8e27-4fe3e011983e/screen-recording-2021-02-19-14:45.webm

The version is 14.4.2

clearing cache and copying to new text file, solved issue.

But this problem is recurring for all files, when i follow the above workflow

**Comment by mfaisalk1** [comment]
just wanted to add to my last comment where I sent the video recording. My powerpoint is 2016 ( if that matters)

**Comment by mararad** [comment]
Thanks for the video. Could you just test this in Incognito mode, please? If it is working, temporarily disable all browser extensions in a preferred browser. I see you have a lot of extensions added so it's worth checking if extensions could be a problem makers in this case

**Comment by mfaisalk1** [comment]
Same issue in incognito mode. Here is the video

https://share.clickup.com/clip/p/t3667419/c864d7d9-9cb9-41f0-b407-3da06094dca5/screen-recording-2021-02-19-15%3A18.webm
