### ISSUE TITLE
Recognize when a diagram has been edited externally and the new version uploaded as an attachment to the Confluence page

### ISSUE THREAD

**Issue by drewburlingame** [jgraph/drawio#1849]
* [ x ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

I would like to be able to edit a local copy of a diagram and upload the file as an attachment to the wiki page.  Currently, when I upload a new version of a file, the editor does not recognize the new version and uses the last version it saved.  This requires me to copy/paste updates into the editor in Confluence.  This prevents use of Atlassian Companion and automated updates to diagrams.

I would like to be able to upload a draw.io file to the wiki page and see the diagram updated in the preview and editor.

If I were an admin of the site, I'd download the wiki text to see if the version number is stored there and update that to point to my uploaded file version.

**Comment by davidjgraph** [comment]
Atlassian companion is more meant for file types that cannot be natively edited within Confluence. What's the workflow case you're trying to solve exactly?

**Comment by drewburlingame** [comment]
Hi David,

For Atlassian companion, the scenario is when I need to edit a document while I'm offline or have an unstable connection.  I can edit with the desktop app and then upload it when done and reconnected.

The automation scenario has the most value for me.  I've been generating dependency diagrams in for our services.  I've been generating to the drawio format because I can control the layout, colors and I can add useful tooltips to each component.  To get these back into confluence, I have to open each diagram locally and in Confluence and then copy & paste, which is not scalable.  Ideally, the same tool could upload the diagram to the page and the update would be recognized by the drawio plugin.

**Comment by davidjgraph** [comment]
Thanks for the clarification. Let me explain the architecture.

A diagram on a Confluence page is a drawio macro, that macro contains the name of the page attachment that contains the data and which revision of that attachment that is currently active.

In your case the attachment revision will increment, but the macro will still point at the previous revision. There's no event that we can listen to that tells us the attachment we depend on has been updated.

The revision parameter is there to maintain a correct audit history across page revisions. If you revert to a previous page the macro (assuming the diagram was changed) will hold the previous revision number.

Problem 1 is that case looks exactly like the external edit case. The macro revision is one behind the attachment revision. If we say always use the latest attachment we break the page history.

Maybe that could be solved with a tag from the external write, though I'm not sure exactly how the desktop build could write a tag.

Problem 2 is that the companion tool with always take the latest attachment version, even if it's not the latest that's being displayed due to page revert. 

It's a complex problem that we haven't thought about in enough detail, tbh.

Are you on server or cloud?

**Comment by drewburlingame** [comment]
Storing the diagram version to associate with page revisions makes a lot of sense.  And I can see how where AC always using the latest version would be an issue.  I'd guess that will be an issue with any type of file that can be edited with macros and I can see why it would be better to only use it for files that can't be edited within Confluence.

If it's possible to update the tag for an attachment from the API, we could do that with the automated tool.  However, if we can also get access to edit pages programmatically, then we could edit the version in the page which seems like a better choice.

Another option could be to add a version chooser to the editor to let us pick a newer version and this could be highlighted when newer versions exist without a draw.io tag.  May seem a bit messy though.  Just spit-balling ideas.

**Comment by drewburlingame** [comment]
Apologies, looks like I forgot to answer your question.  We're on server.

**Comment by davidjgraph** [comment]
OK, I've had a think about both cases and I'd say (2) is the bigger problem. If link the diagram version to a page version there isn't a way to resolve this without changing the way in which you manual edit diagrams.

You might argue that's very rare, but it's data loss when it does happen, even if we find a workaround for (2).

So, for now my suggestion is to change the workflow. To copy a diagram out of Confluence open the diagram in the draw.io editor and copy and paste it out into the desktop tool. Same process in reverse to save it back. 

(2) might be possible to do something in code, but it's a non-trivial amount of testing to ensure all the cases are covered. It will probably be hard to justify the investment, given Atlassian's pro-cloud strategy. But, I'll leave the ticket open in case there is further interest.

**Comment by drewburlingame** [comment]
Fair enough.  If I get API access to edit the page, will I be able to edit the diagram version?  If so, I think that would be adequate to solve the automation issue.  Alternatively, #1851 would allow me to upload SVG with the benefit of the tooltips.

**Comment by davidjgraph** [comment]
Yes, there is a write page API call.
