### ISSUE TITLE
When embed diagram is used, support source page opening in Confluence view mode (instead Edit page mode which we have now) 

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#1939]
"I really like the feature of being able to embed a draw from a source page in multiple other pages. What I do not like is, that each time I want to get to the source page of the draw by using the button in the upper right corner of the embedded draw, it opens the source page (not the draw) in the edit mode. This behavior does not make sense to me because it is not the natural behavior of a link. I would expect to be forward to the page in the normal "view" mode."

Asked in DID-2173

**Comment by Ongrieh** [comment]
Since you labeled this as “feature request” I assume that from your perspektive it is not a bug but actually supposed to work like it is currently working? I think it is a strange behavior that the link in the embedded draw is not forwarding the user to the source page but opening the page (not the draw) in edit mode.

**Comment by Ongrieh** [comment]
I reported that issue initially to @mararad would like to offer my support if the Assignee needs a real life use case 👍

**Comment by ashrafteleb** [comment]
Added, If will be available in the next release

**Comment by Ongrieh** [comment]
@ashrafteleb I am impressed and excited to see it in the wild :)
