### ISSUE TITLE
GitLab linking hangs

### ISSUE THREAD

**Issue by ened** [jgraph/drawio#1961]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

Attempting to open a diagrams.net link from our Wiki gets me to the Diagrams.net page which then forwards to the Authorization in GitLab. Once I click on Authorize I end up in "https://app.diagrams.net/gitlab?code=XXX&state=cId%XXX%26domain%3Dapp.diagrams.net%26token%XXX" (XXX being my replacements) and the page is empty and does not move on.

I have checked the correct session in gitlab.com - the user has the permissions.

**Expected behavior**
Should open the diagram as usual.

**draw.io version (In the Help->About menu of the draw.io editor):**
14.6.8

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] Version 14.1 (16611.1.21.161.3)

**Comment by mbricogn** [comment]
I presume that the problem I am currently experiencing has the same origin but I prefer to make sure: when I click on the link https://gitlab-test-dot-drawdotio.appspot.com/?gitlab=https%3A%2F%2F<LOCAL GITLAB ADDRESS>&gitlab-id=<GITLAB APP ID>#Ambricogn%2Ftn29-p21-is%2Fmaster%2FDroneAraignee.drawio, it uses to open the diagram but since few hours/days, I got the error "An error has occurred - The redirect URI included is not valid". The defined URL has not changed : https://gitlab-test-dot-drawdotio.appspot.com/gitlab.html
Let me know if you would like me to give more details or open a new issue.

**Comment by davidjgraph** [comment]
We've a fix, just trying to sort GitHub in the same release.

**Comment by davidjgraph** [comment]
Fixed in 14.6.9. If you need to force update the PWA go to https://app.diagrams.net/clear.html then back to the app

**Comment by ened** [comment]
@davidjgraph THANK YOU
