### ISSUE TITLE
Deleting shapes with connectors doesn't work with Ctrl+X shortcut

### ISSUE THREAD

**Issue by Bastesque** [jgraph/drawio#1978]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
When I like to delete a shape with the related connector, I can select it (or a specific subset) and then right-click and select the option "Cut". Besides the option it is said that I could also use Cmd+X to do this. But when I use the classic Cmd+X shortcut, only the shape is deleted, not the connector. I know that I can use Cmd+Delete to use both objects at the same time, I just wanted to inform you that the shortcut isn't working.

**To Reproduce**
1. Select a shape that is connected to at least one other shape
2. Richt-Click and choose "Cut". Then try the same procedure with Cmd+X

**Expected behavior**
The shortcut Cmd+X acts the same as the mouse command.

**Screenshots**
<img width="495" alt="Screenshot 2021-05-04 at 14 26 23" src="https://user-images.githubusercontent.com/68647048/117003120-c0142a00-ace4-11eb-8566-6127383b1329.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- I tested it in Confluence Cloud and Server at the latest version of draw.io and Confluence

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release as follows:

- Alt/Cmd/Ctrl+Delete (keyboard shortcut, icon in toolbar, menu and context menu item): Delete cells with edges
- Shift+Delete (keyboard shortcut, icon in toolbar, menu and context menu item): Delete labels
- Cut (keyboard shortcut, icon in toolbar, menu and context menu item): Delete only selected cells

Use Select Edges in context menu to include edges in Cut.
