### ISSUE TITLE
Collaboration Feature without saving on Drive

### ISSUE THREAD

**Issue by ahsanshaokat** [jgraph/drawio#199]
Hi, is this possible to develop collaboration feature without saving on drive. Can we develop this feature through Browser/Local Sharing. I have built some of this functionality by using Heartbeat call, but it's not look's more generic like google drive collaboration. Please help me to develop this feature for local drives/browser as well. Let me know what we can do.

**Comment by davidjgraph** [comment]
This is a bit broad for an issue. If you want to implement a real-time collaboration system hire a software engineer to implement it.

**Comment by ahsanshaokat** [comment]
I am a software engineer, and i just asking that, is there any helping libraries which already builtin in draw.io  to develop this feature, or i have to do it from scratch. I am asking about ( RealtimeMaping.js DriveRealtime.js etc).

**Comment by davidjgraph** [comment]
Not really. The existing real-time is somewhat designed for Google's RealTime API, it's more complex than you need, since it maps out to another data structure, which you wouldn't have to do.

You wouldn't have to use operational transforms, though, not unless you want RT on the label editing. You just need a server acting as a point of truth accepting incoming changes and telling the clients what the correct order of changes were.

**Comment by ahsanshaokat** [comment]
Okay David, Thanks for letting me know.
