### ISSUE TITLE
Invalid redirect URL error when authenticating to private gitlab

### ISSUE THREAD

**Issue by plinss** [jgraph/drawio#1992]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
I'm getting an 'Invalid redirect URL' error when attempting to authenticate against private gitlab instance.

**To Reproduce**
1. Attempt to authorize via a private GitLab instance
2. See error on GitLab page

**Expected behavior**
Authentication should work

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 14.6.11

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: current

**Additional context**
Looking at the URL sent to GitLab, the `redirect_uri` parameter is 'https://diagrams.{mydomain}/gitlab'. In the last version in which this worked, the value was 'https://diagrams.{mydomain}/gitlab.html' (which is also the configured redirect URL in GitLab).

Changing the redirect URL in GitLab to '.../gitlab' instead of '.../gitlab.html' fixes the error on the GitLab side, but authentication still fails because Diagrams doesn't respond to the '.../gitlab' URL, it wants the '.html' extension.

Downgrading to v14.6.2 fixes this, so there was a regression in constructing the `redirect_uri` since then.

**Comment by davidjgraph** [comment]
how are you configuring diagrams.net to reference that private gitlab?

**Comment by plinss** [comment]
I'm setting `window.DRAWIO_GITLAB_URL` in PreConfig.js (as well as `DRAWIO_GITLAB_ID`).

Note that the redirect to GitLab works fine, but it fails when GitLab tries to redirect back to Diagrams. Also, this has been working for some time but started failing in a recent upgrade. 

I believe this broke in V14.6.8, the redirect path from GitLab back to Diagrams changed from `/gitlab.html` to `/gitlab`, but Diagrams is returning a 400 error for `/gitlab`

**Comment by ErikHumphrey** [comment]
I've also experiencing this issue since around the same time as OP while using the Docker image.

**Comment by ErikHumphrey** [comment]
Not sure if it's a separate issue, but similarly, (since about the same time as OP) I've also been getting 404s when trying to create or open a new diagram. Diagrams loads just fine, but no diagrams can be created or opened. Diagrams makes requests to `/gitlab` (causing a 404) when they should be to `/-/draw/gitlab` (which still returns a response successfully). Downgrading seems to work fine.

**Comment by jamespwilliams** [comment]
https://github.com/jgraph/drawio/commit/9425639430927146ef0c52a5dc34f20f0044008b#diff-d0228d4493180df3ed996671a721b16049e6de41f10fdb20752f1d781a3a8573R44 should be `/gitlab.html`, I think.

**Comment by jamespwilliams** [comment]
I'm fairly sure that just changing `/gitlab` to `/gitlab.html` here: https://github.com/jgraph/drawio/blob/d7cf67c98191c693c80e1bf60ac59bac7bb4b8ff/src/main/webapp/js/diagramly/GitLabClient.js#L44 will fix this, but I haven't tested this

**Comment by uritomas** [comment]
I have tried adding the .html and it seems to work, but the following happens:

Describe the bug
The redirection back from my self-hosted gitlab to my diagrams application returns access denied.

To Reproduce
Steps to reproduce the behavior:

1-.Go to save diagrams in gitlab
2-.Click on create new diagram, and click blank diagram, create. Click authorize.
3-.Authorize redirects to sign up private gitlab, enter the user and password. The url that I get: " https://gitlab.genos.es/oauth/authorize?client_id=my_id}&scope=api%20read_repository%20write_repository&redirect_uri=https%3A%2F%2Fmy.company.com%2Fdiagrams%2Fgitlab.html&response_type=code&state=cId%3D{my_id}%26domain%3Dmy.company.com%26token%3D%3C!DOCTYPE%20html%3E%0A%3Chtml%3E%0A%09%3Chead%3E%0A%09%09%3Ctitle%3E%3C%2Ftitle%3E%0A%09%3C%2Fhead%3E%0A%09%3Cbody%3E%0A%09%09This%20window%20will%20be%20closed%20automatically.%0A%09%09%3Cscript%3E%0A%09%09%09if%20(window.opener%20!%3D%20null%20%26%26%20window.opener.onGitLabCallback%20!%3D%20null)%0A%09%09%09%7B%0A%09%09%09%09try%0A%09%09%09%09%7B%0A%09%09%09%09%09var%20search%20%3D%20window.location.href%3B%0A%09%09%09%09%09var%20idx1%20%3D%20search.indexOf(%27access_token%3D%27)%3B%0A%09%09%09%09%09var%20code%20%3D%20null%3B%0A%09%09%09%09%09%0A%09%09%09%09%09if%20(idx1%20%3E%3D%200)%0A%09%09%09%09%09%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%09%09%09var%20idx2%20%3D%20search.indexOf(%27%26%27%2C%20idx1)%3B%0A%09%09%09%09%09%09code%20%3D%20search.substring(idx1%20%2B%2013%2C%20idx2)%3B%0A%09%09%09%09%09%7D%0A%0A%09%09%09%09%09%2F%2F%20Continues%20execution%20of%20main%20program%20flow%0A%09%09%09%09%09window.opener.onGitLabCallback(code%2C%20window)%3B%0A%09%09%09%09%09window.close()%3B%0A%09%09%09%09%7D%0A%09%09%09%09catch%20(e)%0A%09%09%09%09%7B%0A%09%09%09%09%09alert(%27GitLab%20error%3A%20%27%20%2B%20e.toString())%3B%0A%09%09%09%09%09window.close()%3B%0A%09%09%09%09%7D%0A%09%09%09%7D%0A%09%09%3C%2Fscript%3E%0A%09%3C%2Fbody%3E%0A%3C%2Fhtml%3E ".

4-. Click on "authorize" and redirect to my application and error appear: Error Access Denied.

Expected behavior
Gitlab should give me permission.

Additional context
I think the url parameters are not correct, Is it possible? We have the last version.
Thanks

**Comment by ashrafteleb** [comment]
Gitlab authentication is changed to use server secret instead of the insecure implicit authentication
As I understood, this issue is related to self-hosted draw.io, please note that the new authentication method requires running the Java backend (cannot be hosted as a fully static html site). In addition, you need to create an app in Gitlab and set the app client id/secret in the files:

gitlab_auth_url
gitlab_client_id
gitlab_client_secret 

We'll try to update the docker image soon to handle Gitlab

Meanwhile, @plinss let us know the exact setup you are using to run draw.io

**Comment by plinss** [comment]
I'm using the jgraph/drawio docker image behind a simple Nginx reverse proxy for TLS termination. I'm mounting a local PreConfig.js and PostConfig.js (Method 3 in the docs) and am setting `window.GITLAB_URL` and `window.GITLAB_ID` in PreConfig.js. We have a local GitLab instance. This setup works with version 14.6.6 and before of the Docker image.

**Comment by davidjgraph** [comment]
Everyone needs to read this comment https://github.com/jgraph/drawio/issues/1992#issuecomment-860238380 . Implicit grants (pre 14.6.7, I think) and not allowed any longer by Gitlab, https://gitlab.com/gitlab-org/gitlab/-/issues/288516.

They have security problems, so Gitlab are switching them off. You need to:

- create a project at the [applications page](https://gitlab.com/-/profile/applications)
- copy the ID and secret to the files mentioned
- set the github auth url to the correct path for your Gitlab instance. The public instance is https://gitlab.com/oauth/token
- set the callback URL to https://YOUR_DOMAIN/gitlab
- set confidential to yes
- add scopes:
    api (Access the authenticated user's API)
    read_repository (Allows read-only access to the repository)
    write_repository (Allows read-write access to the repository)

**Comment by plinss** [comment]
@davidjgraph First, maybe I missed something, but this is a significant change to have slipped into a minor release with no obvious warning or documentation. And while I respect your being proactive in supporting GitLab's change, and the more secure authentication mechanism, the current mechanism does still work and won't be removed from GitLab for several more releases.

Second, I tried following your instructions, and it still fails (with V14.7.8) (and is this process documented anywhere?). When GitLab redirects back to Diagrams I get a blank page and a 500 error (with no further information in the dev tools, I'm happy to check logs if you tell me what would help here). FWIW, I'm authenticating against a local GitLab instance running the current release.

Third, @ashrafteleb mentioned the Docker image needing to be updated, so is this simply not working yet when running from that? (as I am)

**Comment by ashrafteleb** [comment]
@plinss What I meant is we need to test the Docker image and write the proper documentation similar to Google Drive/OneDrive and do any needed changes if any.

Meanwhile, you can help us by checking tomcat logs inside the container

**Comment by davidjgraph** [comment]
@plinss Yeah, fair point. Our existing versioning is based around the version we deploy, it's not designed for the case of a custom deployment. It's pretty out of date in that regard, we'll have a think how to improve it.

**Comment by trocster** [comment]
had to change the "http-nio-7070" port because of a conflict when running locally (puma ?) 

Catalina is started via a "run"  (not "start") so logs all are going to stdout[0], albeit at the default verbosity level.

Also tried to follow the comment/instructions and it also fails using version 14.8.5 after the gitlab "Authorize drawio to use your account?"

Using: 

` docker run -it --rm -e DRAWIO_GITLAB_ID='*' -e GITLAB_CLIENT_SECRET='*'  -e GITLAB_AUTH_URL=https://gitlab.domain.com/oauth/token --name="draw" -p 7070:7070 drawio`

and using the call back / redirect url with out the .html, to give a blank page with status code 400. The favicon loads after it.

The last entires in the log are:
`
 08-Jul-2021 23:40:52.138 INFO [http-nio-7070-exec-4] com.mxgraph.online.AbsAuthServlet.doGet AUTH-SERVLET: [172.17.0.1] Found cookie state (*  -> *)`

and the last uRL is  http://localhost:7070/gitlab?code=*&state=cld=*&domain=localhost&token=*

[0] https://stackoverflow.com/a/50730492/2568021

**Comment by thefuckingcode** [comment]
> had to change the "http-nio-7070" port because of a conflict when running locally (puma ?)
> 
> Catalina is started via a "run" (not "start") so logs all are going to stdout[0], albeit at the default verbosity level.
> 
> Also tried to follow the comment/instructions and it also fails using version 14.8.5 after the gitlab "Authorize drawio to use your account?"
> 
> Using:
> 
> ` docker run -it --rm -e DRAWIO_GITLAB_ID='*' -e GITLAB_CLIENT_SECRET='*' -e GITLAB_AUTH_URL=https://gitlab.domain.com/oauth/token --name="draw" -p 7070:7070 drawio`
> 
> and using the call back / redirect url with out the .html, to give a blank page with status code 400. The favicon loads after it.
> 
> The last entires in the log are:
> ` 08-Jul-2021 23:40:52.138 INFO [http-nio-7070-exec-4] com.mxgraph.online.AbsAuthServlet.doGet AUTH-SERVLET: [172.17.0.1] Found cookie state (* -> *)`
> 
> and the last uRL is http://localhost:7070/gitlab?code=*&state=cld=*&domain=localhost&token=*
> 
> [0] https://stackoverflow.com/a/50730492/2568021

if i run this on my own website, what environment variable should i confiure for authorizing from github?is there any doc for OAUTH ?

**Comment by davidjgraph** [comment]
This is a thread about gitlab, not github.

**Comment by plinss** [comment]
FWIW I'm still seeing this issue with v16.2.4
