### ISSUE TITLE
Support global default style for connector labels - font family, font size, background color

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#2140]
"I'm trying to customize our draw.io via Confluence Server, everything seems to be fine except for one thing - I can't figure out how to define the default style for connector labels - font family, font size, background color. Is it possible?"

Asked here: https://app.intercom.com/a/apps/fz6gxyi6/inbox/inbox/994666/conversations/55912901555561

P.S. I suggested experimenting with "defaultEdgeStyle" and font family/font color. I tested them but this doesn't always work due to multiple factors included (e.g. if the newly label is added or old one edited etc.) so the issue is created.

**Comment by bandantonio** [comment]
I manage to resolve the issue by placing the parameters at the beginning of the `defaultEdgeStyle` object:

```js
"defaultEdgeStyle": {
    "fontFamily": "Verdana",
    "fontSize": "14",
    "fontColor": "#d2d2d2"
    ...
    // other parameters
},
```
When placed in the middle or at the end of the object, these parameters were ignored and draw.io was applying standard styling to labels.

I believe **this information must be added to the documentation** because in my case the need for strict order and precedence of parameters is not obvious and it's a long "try and fail" path to figure this out.

**Comment by mararad** [comment]
Thanks. Is it possible to record a video showing how the labels are changed exactly when parameters are put at the beginning? 
 I would like to be sure I am performing the same steps as you are. I see you are using drawio 9.5.3 and Confluence Server 7.8.3 
I tried your solution and it failed at my place so I assume this could be related to drawio version.

What OS and browser version are you using?

Regards,

**Comment by alderg** [comment]
This also seems to work when placed in the middle or at the end of the object. What config did you try where it failed?
