### ISSUE TITLE
Diagram alignment in page editor

### ISSUE THREAD

**Issue by borisjgraph** [jgraph/drawio#2181]
As reported in [DID-3058](https://drawio.atlassian.net/jira/servicedesk/projects/DID/queues/custom/70/DID-3058)
"The diagrams are aligned to the left although they are aligned to the center in the editor"

**Comment by borisjgraph** [comment]
This doesn't seem to be worked for other 3rd party plugins I tried.

**Comment by davidjgraph** [comment]
A bit of history first. Before release 9.6.4 we didn't have a wrapper div around the drawio viewer. In July 2021 an Atlassian developer contacted us and told us we were required to add a div because otherwise the page inline commenting functionality had problems with words that were in diagrams when users tried to select the same words in text to comment on.

After a discussion it turned out that this "requirement" wasn't written down anywhere, but without the change inline comments would be a problem on-prem, so we added the div. Testing didn't show up any problems.

The problem, it turned out later, was that alignment broke. This is a both center and right alignment, they always left aligned.

We tried to fix this by styling our extra div, but couldn't find a solution that worked properly. Unfortunately, we were then left with a choice of either having inline commenting malfunctioning or alignment always setting to the left. We've decided on keeping the fix for inline commenting.

I know this doesn't help those with the alignment issues (though there is a workaround shortly), but macro alignment is broken for a large number of both Atlassian and third party macros, https://jira.atlassian.com/browse/CONFSERVER-35605. However, Atlassian have declined to provide a solution to the issue on-prem.

Our workaround, available in 9.8.0, will be to set the draw.io viewer to simple viewer. That embeds an image that will be correctly positioned.
