### ISSUE TITLE
Hyperlink bleeding into overlaying container

### ISSUE THREAD

**Issue by jerryhall** [jgraph/drawio#2220]
I'm using the current (15.0.3) online free version of diagrams.net.

I'm having an issue when opening containers over hyperlinked objects below and outside the container. When I hover my mouse the outline of the lower hyperlinked object appears and is clickable. In the images you can see the purple outline of the hyperlinked object outside of the container.

In my case I have hyperlinked elements in the container as well so it's conflicting visually and UX-wise with those as well.

Is this a feature or a bug and is there a way around it so I can continue using these features?4

Thank you!
![bleeding-links-both](https://user-images.githubusercontent.com/3231824/131580790-e6e39d9c-5c37-4e61-a665-e05d49c241b3.png)

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release.

**Comment by davidjgraph** [comment]
For any users that have implemented an image map style of functionality, the change in this issue is a valid bug fix. The backward shape should not be reacting in the viewer, unless it is the topmost shape under the mouse.

If you want an image shape, place a transparent shape on top of the area and add the link to that.
