### ISSUE TITLE
Alpha/Trasparency

### ISSUE THREAD

**Issue by BloodyIron** [jgraph/drawio#244]
Any chance we could get support for Alpha/Transparency in imported images please?

**Comment by BloodyIron** [comment]
It was a team member who brought this to my attention. I'm going to try and dig up more info and report back!

**Comment by BloodyIron** [comment]
Bump, still need this!

**Comment by davidjgraph** [comment]
We need specific reproduction steps please to keep this open.

**Comment by BloodyIron** [comment]
So why did you tell us then close it minutes later? Come on...

**Comment by davidjgraph** [comment]
The timeline as I read it

15 Apr 2018 Issue filed
19 Apr 2018 Clarification requested "Could you be more specific, please?"
19 Apr 2018 Response of no, but I will come back.
05 Jul 2019 Bot marked as stale, 15 months after request for more information.

I closed it because in 15 months you have not responded to the request for more information.

**Comment by eggbean** [comment]
When I paste in images with alpha channel transparency from Photoshop, what should be transparent areas are shown with a white background. Is this the current state of the things or am I doing something wrong?

![Image](https://github.com/user-attachments/assets/2848e253-714b-4e94-8284-e096176dfef7)
