### ISSUE TITLE
restore "Reverse" Functionality

### ISSUE THREAD

**Issue by chewontoast300** [jgraph/drawio#2569]
I tried searching for an issue or FAQ related to removing the option to REVERSE a line but could not find anything.
Is this a intended removal in the latest versions, or was this a mistake perhaps?
I definitely use this function regularly when making wiring and routing diagrams as it is more convenient than changing the beginning/end of line repeatedly on a project that i cant connect to edge of item.

**Comment by alderg** [comment]
The function was accidentally disabled for edges in the arrange menu. This will be fixed in the next release. You can still reverse the edge by selecting it and pressing Ctrl+R or clicking this button in the format panel on the right:
![Screenshot 2022-01-21 at 08 35 50](https://user-images.githubusercontent.com/921200/150486121-080e88c9-b678-4ce7-9f18-6cf0256a2be9.png)
