### ISSUE TITLE
Edit connection points of groups

### ISSUE THREAD

**Issue by ghost** [jgraph/drawio#2606]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
As introduced shortly editing the connection points of a shape with an editor, this seems not to work with groups. I am able to open the connection points editor, but not as for shapes the group is not visible and when editing connection points, they do not appear in the group after applying

**To Reproduce**
1. Create two rectangles
2. Group the rectangles together
3. Right click -> Edit Connection Points
4. Edit the position of the connection points

**Expected behavior**
The connection points are visible on the group after applying

**Screenshots**
![grafik](https://user-images.githubusercontent.com/98887275/152152645-cec256d2-69ab-488b-b40b-e28eb5719e06.png)
Edit connection points for a group
![grafik](https://user-images.githubusercontent.com/98887275/152152626-48d6383d-3036-45bb-a6af-f2b08727d2ca.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 16.5.1

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by timboxyz** [comment]
I can confirm this and reported it in the drawio.desktop repo (#902) as I didn't think to look in this repo too for an existing report.

**Comment by Murmele** [comment]
in 20.2.3 the option for editing of connection points for groups is anymore available. Will it come back?

**Comment by davidjgraph** [comment]
@Murmele could you file a seperate issue please?

**Comment by Murmele** [comment]
Yes I will do. Thank you!

**Comment by mrtoikka** [comment]
Going to ping this issue to see if I can get it back on the radar. I am using 24.2.5. like the OP, I am able to group two items, and with the group selected, I can edit connection points. However, they don't appear to work - after setting them. All I can see when hovering over the group to draw connections are the original shape's connections points.

**Comment by alderg** [comment]
Try making the group connectable:
<img width="231" alt="Screenshot 2024-05-29 at 06 02 56" src="https://github.com/jgraph/drawio/assets/921200/9702db2e-a84c-44f5-9411-2c6d7b28fadf">

**Comment by mrtoikka** [comment]
After selecting "connectable" as shown, the new specified connection points now show up, but they are impossible to get anything to snap to. They only appear when dragging a connection over the edge of the group, and disappear before you can get to the connection point. Is there a way to make connection points snap-able without having to be on the edge of a shape/group?

**Comment by alderg** [comment]
What's the use case?

**Comment by mrtoikka** [comment]
For being able to connect custom groups or elements that don't exist in the libraries/elements provided.

**Comment by mrtoikka** [comment]
To further elaborate, I'd like to set connection points for the group so that I can draw lines to them that will stick when I move the group around. For example, in the attached image, I created a group of lines and a rectangle on the right side. I then set connections points for the group (hard to see, circled in red) and made the group connectable. However, I cannot get the line on the left to snap or connect to the connection point. The connection points for the group wont even show up unless I place my cursor directly over the outer perimeter of the group (shown with a red X). 
<img width="843" alt="Screenshot 2024-06-06 at 11 56 11 PM" src="https://github.com/jgraph/drawio/assets/45864914/f52be94b-eb2c-49d7-8ae9-c2fc40f2e998">

**Comment by davidjgraph** [comment]
could you share that exact diagram model data please here.

**Comment by mrtoikka** [comment]
Man, when it rains it pours... I did not save the file that I created that demonstration/example from. Tried to reproduce the issue today to send as requested, but now I am now unable to get a group’s connection points to appear at all (even after making it connectable).

Made a quick recording to show what I was doing, can't upload because it's too large. Tried to redo recording with smaller window, now recording are all distorted... *sigh*

Steps to reproduce the issue:

1. Create new drawing
2. Drag 3 lines into drawing and arrange as that sideways looking Y I showed in an earlier screenshot
3. Copy + Paste said Ys and arrange until you have 4 of them
4. Drag a rectangle in, Arrange -> To Back, then resize/position as shown in previous screenshot
5. Click+drag to highlight the whole mess
6. Right click and select Group
7. I usually left click off of the group, then left click the group once, to make sure I have the group selected and none of it's members, then I expand the properties and make the group connectable
8. I then click the drop down list to select edit connection points, and move a few of the existing points inwards, then click apply.
9. I then drag another line into the drawing, and attempt to connect it to the moved group connection points...

If I'm able to reproduce it again, I'll send a file... not sure what changed. If there's a dropbox other than here I can drop the record to (25mb) let me know.
