### ISSUE TITLE
Dropbox Link problem when using GitHUb pages

### ISSUE THREAD

**Issue by planetahuevo** [jgraph/drawio#269]
Hi, 
I am trying to use the app from the github repo directly with github pages. 
The system works fine but when trying to use the OneDrive connection (or any other one), the url is not working. 
the message from (for example) dropbox is: 

```
More details for developers
Invalid redirect_uri: "https://XXXXX.github.io/dropbox.html": It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).
```

And of course on that address is not the dropbox.html, because it is at 
`src/main/webapp/dropbox.html`

No idea how to make this work, if it is possible at all. 

Thanks

**Comment by davidjgraph** [comment]
Third-party cloud storage providers want a list of domains that the app runs on for that Dropbox API project. We can't whitelist github.io since then anyone could use our project with arbitary code and get us banned.

You would need to create a new Dropbox app project and use that project API in the codebase. However, I would strongly advise against whitelisting github.io for the reason I mention.
