### ISSUE TITLE
Feature request: CSV Import - support an ability to style or place an element into a layer, set layer z-order

### ISSUE THREAD

**Issue by npiper** [jgraph/drawio#2892]
* [ Y ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ Y ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Our team has successfully used the import CSV feature to create complex diagrams with over 100 elements including meta-data.

We often like to have the ability to use different layer visibility so certain items can be hidden, displayed during demo's.

Having extra import control over putting an element into a particular layer during the import process would save a lot of time manually doing this task post import.

The ability to change, and manipulate relative z-order as part of this may be useful as well (e.g from -10 lowest to +10 highest)

**Describe the solution you'd like**

The CSV syntax for import supports a 'layers' array with a named relative z-order and a column in the CSV can be mapped to the Layer name.

No layer id puts the element into the `background` default layer

```
#layername: layerId
# layers {\
# "Layer0" : "label="Layer 0;zOrder=10;",\
# "Layer1" : "label="Layer1;zOrder= 9;"}
```

**Describe alternatives you've considered**

As far as aware no alternative exists for assigning shapes to layers during CSV import.

**Additional context**

**Comment by terefang** [comment]
+1

**Comment by davidjgraph** [comment]
I want to thank you for your time, effort, and thought that went into outlining your feature proposal. We appreciate the ideas and feedback we receive from users like you, as it helps us understand the evolving needs of our community.

After careful review and discussion with our development team, I regret to inform you that we are currently unable to accommodate your request. As a growing company, we have to prioritize the allocation of our resources to ensure that we are developing features and improvements that can cater to the needs of the majority of our users.

While we recognize that your request is valid and holds potential for specific use cases, our analysis suggests that it might be more of a boundary case rather than a mainstream functionality. This means that while the feature could be useful for certain scenarios, it might not be applicable or beneficial to a large proportion of our user base.

We apologize if this news is disappointing, we appreciate your understanding in this matter and thank you for your continued support.
