### ISSUE TITLE
Feature to create a new folder in the cloud

### ISSUE THREAD

**Issue by Atalanttore** [jgraph/drawio#2980]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
To save a new diagram for a new project, I wanted to create a new folder in my Google Drive within Draw.io, but that feature doesn't seem to exist.

**Describe the solution you'd like**
I would like to be able to create folders in my Google Drive within Draw.io.

**Describe alternatives you've considered**
Creating a new folder in the web interface of Google Drive also works, but makes the workflow worse.

**Comment by davidjgraph** [comment]
We have to use the Google supplied picker, that does not offer a new folder option. This request would have to be directed at Google, unfortunately, there is no action we can directly take.

**Comment by Atalanttore** [comment]
Google unfortunately has no intention to add a feature to create a folder.
See https://issuetracker.google.com/issues/241704328#comment2

This feature is now up to the developers of Draw.io.

**Comment by davidjgraph** [comment]
Their answer is correct, it's an file picker.

I don't think you understand the security implications of your request. Currently, the picker is entirely on the google domain and just passes the ID of any file(s) selected to us.

To change the picker, we would have to write our own picker, which we're not going to do.

Additional, the permissions of the app would have to change just for this picker. Instead of only being able read files specific to drawio, we'd have to expand the permission to read all files, to replace the functionality of the google picker. This would affect 10s of millions of accounts that have connected with the current permissions, that's not going to happen.
