### ISSUE TITLE
Upgrade mermaid-js

### ISSUE THREAD

**Issue by cmdares** [jgraph/drawio#2981]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the solution you'd like**
Upgrade mermaid-js to the latest version to use new features such as themes.
https://mermaid-js.github.io/mermaid/#/theming
Thanks.

**Comment by max1c** [comment]
This would be great. The 'link' feature is also not supported in the current version.

**Comment by davidjgraph** [comment]
Thank you for your message regarding the mermaid integration in draw.io. We appreciate your interest and would like to inform you that our team is committed to keeping mermaid up-to-date with the latest improvements and security updates.

However, due to resource limitations, we may not be able to update mermaid as frequently as we would like. Our priority is to ensure the security of our platform and any security holes in mermaid will be updated more quickly.

Regarding your request, we suggest checking whether the mermaid features you require have already been integrated into draw.io. If they have, you can start using them right away. If not, we apologize for any inconvenience and suggest considering other ways to achieve the desired outcome.

Thank you for your understanding, and please do not hesitate to contact us if you have any further questions or concerns.

**Comment by jeeftor** [comment]
Themes have not been added ... because they are a v10 feature I think.
