### ISSUE TITLE
Add hachureGap for non-sketch styles

### ISSUE THREAD

**Issue by svew** [jgraph/drawio#2994]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm trying to create a diagram with many different arrow types, and "hatch" seemed like a great pattern for one of my thicker arrows, but the hatch pattern is so far apart currently on my graph that it's hard to tell sometimes if an arrow has a hatch pattern, especially if it's a short arrow.

**Describe the solution you'd like**
Add hachureGap (which already exists) and maybe hachureWidth/hachureAngle properties to non-sketch mode arrows (already exists for sketch-mode, but the UI doesn't make them available)

**Describe alternatives you've considered**
Using sketch mode, but couldn't figure out all the properties I'd need to change to make them look like the base arrow I wanted to

**Additional context**

**Comment by ultrakult** [comment]
I'm hijacking this issue, because I'm also trying to use the new hatching feature. I need it for a printable version in black and white / monochrome (work printers... right?). 

Though the feature might work well for boxes, arrows with hatching look kind of not so good. Spacing, width and angle of the hatching would open the options far more to fine tune the looks. 
Also the hatching seems to be dependent on the zoom level. I don't like that. 

I want to show my appreciation for this project! Very well maintained and so many features added regularly, that's just plain amazing! My diagrams never looked better!
