### ISSUE TITLE
Image exported as giant cross mark

### ISSUE THREAD

**Issue by Kanhoto** [jgraph/drawio#3004]
**Describe the bug**
When I try to export a page with an image, some of them export well but the last ones I put in my diagram are exported as cross marks.

**To Reproduce**
1 - Hosting an image like this one https://postimg.cc/cvPMZzjg/842344e1
2 - copy and paste it into a page of diagram
![image](https://user-images.githubusercontent.com/85866455/185852260-53bf3316-e004-4790-9d1b-63656125629d.png)
3 - Export it as a png and get that
![image](https://user-images.githubusercontent.com/85866455/185852359-b0772923-9bd9-4dcb-8104-fca6b8be5abf.png)

**Expected behavior**
Exported image

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.5...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version v1.42.97

**Additional context**
It worked with my first images, but it stopped working now and I dunno why 
Tried deleting some images because I thought there was a limit to the number of png but I was wrong since it didn't work

**Comment by davidjgraph** [comment]
Is it an issue with Brave? Does it work on a different browser?

**Comment by Kanhoto** [comment]
I tried with Edge by microsoft, but same thing

**Comment by alderg** [comment]
Please attach the diagram file.

**Comment by Kanhoto** [comment]
Here it is 
https://drive.google.com/file/d/1AAQ58W3R6Ur6bRj9Ryez_8IWO4ja1S3J/view?usp=sharing

(really feel like I'm dumping my work on you, sorry ^^)

**Comment by alderg** [comment]
For some reason, that image URL https://i.postimg.cc/Zq5fPtxc/App-Robot-Controller-final.jpg seems to return a 302 (redirect) when we try to get the binary data for the image via our proxy servlet (which is required for the client-side image export to work). This also happens when you try to access that URL in Chrome with the debug console open, but not with the debug console closed. I'd recommend to use another image hosting provider.

**Comment by Kanhoto** [comment]
It's like you said, it work with another website.

Strange though, since I used the same ones for all images
