### ISSUE TITLE
Having two tabs of the same project open cancels progress save, lost hours of work

### ISSUE THREAD

**Issue by Mozoloa** [jgraph/drawio#3099]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Having two tabs of the same project open cancels progress save, lost hours of work this afternoon, after something was glitchin in the interface, so I had to refresh to find all my hours of work were entirely gone, **the revision history showed plenty of backups every minutes yet they were all the same unchanged drawing, aka the one I started working on earlier today**

**To Reproduce**
1. Create a drawing on google drive
2. Duplicate the tab (probably did that by mistake as I have several different open)
3. Do things on the first tab
4. Nothing happens on the second tab and it's the one that seems to be save (your work is going nowhere)

**Expected behavior**
It should save the active tab only or mirror the active tab as it does when some collaborator is editing the project

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.4.0

**Desktop (please complete the following information):**
 - OS: W11 latest
 - Browser Brave
 - Version
![image](https://user-images.githubusercontent.com/20817233/195424197-b12a1823-9d92-428c-92c3-51d8ddfae6a6.png)

**Comment by Mozoloa** [comment]
Nope, had to redo the whole thing

**Comment by RobertDanhi** [comment]
I found it, turns out I was signed on with a different email


Chef Robert Danhi
***@***.***
www.ChefDanhi.com
Mobile: 310.625.1258

Cent frm ifone, plese excse tyops ;)

CONFIDENTIALITY NOTICE: This e-mail and any attachments are for the exclusive and confidential use of the intended recipient. If you received this in error, please do not read, distribute, or take action in reliance upon this message. Instead, please notify us immediately by return e-mail and promptly delete this message and its attachments from your computer system.
