### ISSUE TITLE
Display layers in Select page and Layers section as a simple list

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#3300]
"When I need to setup in the DrawIO plugin the layers of the diagram which I want to display, it generates the previews of each layer and it takes a great amount of time. This is useless, and the names of the layers are not fully displayed in the view. A simple list would be much more efficient.“

Asked in DID 7200 
![layers](https://user-images.githubusercontent.com/44292306/213421834-5248d704-6285-4628-b69a-bdb2240a19cf.png)

**Comment by meramad** [comment]
I confirm this. The DrawIO application (or Diagram.Net) is a feature-rich diagram editor that can be used to create highly complex diagrams, not just simple ones with only a few layers. Therefore all interfaces related to the layers, especially the drawio plugin in confluence, should support many layers. The current interface sometimes makes it impossible to find the layer the user would like to display. The generated preview for each layer should be optional because it takes a lot of time, and in the case of many layers, it is not really practical. I imagine, for example, a simple pop-up list where the user can read the full name of each layer and select with a checkmark if he wants the layer to be included in the view. And if the user would like quickly check the content of the specific layer, then he should be able to click on it on the list, and the preview shall be rendered only for that specific layer, not for all.
