### ISSUE TITLE
Removing a group from another group is not working.

### ISSUE THREAD

**Issue by NivruthaB** [jgraph/drawio#3510]
When we remove a group from another group, the removed group is still part of the bigger group. 

Steps to reproduce the behaviour:
1. Create a group. 
2. Add this group to another group. 
3. Now, remove the group from the bigger group. 

**Current behaviour:** 
We can see that the group is still part of the bigger group. 
**Expected behaviour:** 
We should be able to remove groups from other groups.

Video recording to demonstrate the problem: 

https://user-images.githubusercontent.com/86827455/231991140-899f3e41-6253-4273-bfb8-c0093e5c09c0.mp4

We can see here that the removed group moves along with the bigger group, but when we remove an individual shape, it works as expected. 

draw.io version 21.1.6

Desktop (please complete the following information):
OS: macOS
Browser: Chrome
Version: macOS Ventura 13.2.1

**Comment by alderg** [comment]
Thanks for the report. This will be fixed in the next release. As a workaround, select the group to be removed and click "Remove from group" in the Arrange panel:

<img width="239" alt="Screenshot 2023-04-14 at 11 40 47" src="https://user-images.githubusercontent.com/921200/232009022-e358b9a6-4e74-45f0-be55-7fd6237e68d4.png">

**Comment by davidjgraph** [comment]
Released in 21.1.8

**Comment by NivruthaB** [comment]
Thank you!
