### ISSUE TITLE
"aws4" icons missing from repository

### ISSUE THREAD

**Issue by jpeddicord** [jgraph/drawio#356]
Hi! I see that the newer AWS icons are available on draw.io under the AWS18 name: https://www.draw.io/?splash=0&libs=aws4

Thanks for adding these. I can't quite find these in this repository, however (at least in the stencils directory). Should I be looking elsewhere? If not, could these be added?

Full disclosure: I work for AWS; happy to help figure things out if there's any issues.

**Comment by davidjgraph** [comment]
Looks like we had a sync error on the latest build (Github is a mirror). I'll take a look, but while I have you can I ask a sneaky favour back...

We have a number of support tickets filed against us by users of https://drawio.corp.amazon.com, which I'm guessing is the internal instance Amazon runs. They don't seem to understand it's nothing to do with us (which makes the threads longer), but is there any way to inform users to deal with your internal IT rather than us? Appreciate any help.

**Comment by jpeddicord** [comment]
Thanks for checking.

Regarding the support tickets, ouch, sorry about that. ☹️ I had thought I'd patched out all direct lines of contact to you all to avoid that, but that might not have been enough. I'll double check that and add in some help/contact links to our internal support resources to hopefully stop that.

**Comment by davidjgraph** [comment]
Cool, thanks for your help. Sync problem fixed, you can draw some new style diagrams quick for reinvent 😎
