### ISSUE TITLE
Enable embed.diagrams.net version pinning to prevent bugs in production environments

### ISSUE THREAD

**Issue by Ogglas** [jgraph/drawio#3566]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Even though your response time is excellent it would be much appreciated to upgrade `embed.diagrams.net` versions manually by first testing it out in dev and stage environments. We noticed the bug below in our production environment and around 500 users were affected as their cached working versions started to expire:

https://github.com/jgraph/drawio/issues/3563 

**Describe the solution you'd like**

Enable a version pin using URL parameters. For example to load [v21.2.1](https://github.com/jgraph/drawio/releases/tag/v21.2.1) that did not have the bug mentioned above you could load `https://embed.diagrams.net/?v=21.2.1`. 

This version parameter could then be used in your example [diagram-editor.js](https://github.com/jgraph/drawio-integration/blob/master/diagram-editor.js#L66) as well.

**Describe alternatives you've considered**

An alternative would be self hosting but if versioning was offered it would be a good alternative.

**Comment by davidjgraph** [comment]
It makes sense as a suggestion. Thinking further about it my reasons against would be:

- 21.2.8, the release the problem was noticed in, was a security release fix. The temptation would be for users to stick with a version that works and there'd never be time to update and then up not benefiting from us having an active security program.
- We don't currently have every single release version hosted. Generally, we go back about 30 versions. We don't monitor usage (it would breach our privacy policy) so we wouldn't know it someone is using the version we're about to delete.

There's no back-end involved with embed. You can host it as a static site and control updates but pulling from our repo.

At the simplest, clone the repo and publish to github pages (this repo publishes to https://jgraph.github.io/drawio/src/main/webapp/index.html). That gives you site statically served at the version you pull. You just need embed=1 in the url parameters to force embed mode. If traffic were high you could put cloudflare in front.

The other issue is that our testing didn't pick up on the issue. We do use embed in production, but not in this way.

We can think about the testing, but really the whole point of making the project open source is to give you the power to control the versioning (and uptime even) in this way. 

I'm going to decline, for reasons:

- I think the self-hosting route is simple enough and address the issue.
- I don't want want us to take on the responsiblity of uptime for an arbitary number of historic versions.
- I don't want us to take the responsibility of us hosting versions with known security holes and users using those.

Hope that makes sense.
