### ISSUE TITLE
Not a diagram file (error on line 41 at column 57: xmlParseEntityRef: no name)

### ISSUE THREAD

**Issue by CanDaikin** [jgraph/drawio#3643]
Hello , what is the reason for the error below ? 

<!DOCTYPE html>  <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <title>Süreçler 2 Update.drawio - draw.io</title> <meta name="application-name" content="diagrams.net"><meta name="apple-mobile-web-app-title" content="diagrams.net"> <meta name="Description" content="draw.io is free online diagram software for making flowcharts, process diagrams, org charts, UML, ER and network diagrams"> <meta name="Keywords" content="drawio, diagram, online, flow chart, flowchart maker, uml, erd"> <meta itemprop="name" content="draw.io - free flowchart maker and diagrams online"> <meta itemprop="description" content="draw.io is a free online diagramming application and flowchart maker . You can use it to create UML, entity relationship, org charts, BPMN and BPM, database schema and networks. Also possible are telecommunication network, workflow, flowcharts, maps overlays and GIS, electronic circuit and social network diagrams."> <meta itemprop="image" content="https://lh4.googleusercontent.com/-cLKEldMbT_E

**Comment by davidjgraph** [comment]
No idea, please attach the file.

**Comment by CanDaikin** [comment]
Not allowed to attach the file via web. Please find attached.

**Comment by davidjgraph** [comment]
zip it first before attaching

**Comment by CanDaikin** [comment]
[l.zip](https://github.com/jgraph/drawio/files/11660180/l.zip)

**Comment by mararad** [comment]
Hi,

The file you attached shows you saved whole browser page as HTML instead diagram as XML. 

In order to save a diagram you should use diagrams.net File > Save (as) or click red "Unsaved changes"
![save from the editor](https://github.com/jgraph/drawio/assets/44292306/5600fb47-9a66-47a0-a2d7-2acab654571c)

You probably used browser menu Save as and that is the reason why you are experiencing the problem with the file
![save from browser](https://github.com/jgraph/drawio/assets/44292306/13a5cf08-d398-48f0-973b-3afe646d1538)
