### ISSUE TITLE
Import Powerpoint shapes as editable shapes in drawio

### ISSUE THREAD

**Issue by hillush** [jgraph/drawio#3671]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have a Powerpoint, which I want to display as a drawio diagram in Confluence Cloud. Right now I have to either
a) import as a picture and hope that I never have to change anything
b) rebuild the slide deck with drawio shapes

**Describe the solution you'd like**
I would like to have the possibility to import PPT-shapes as editable shapes in drawio. CTRL C --> CTRL V is optimal ...

**Describe alternatives you've considered**
... but exporting and importing via some dialog is also a good solution

**Additional context**
We are moving a lot of content to Confluence Cloud. This feature would make this job easier and create a lot more acceptance for drawio from my colleagues

**Comment by isalew** [comment]
The main disconnect for me is that lots of software architecture diagrams have humble beginnings in slide decks. They get massaged through pre-sales and discovery cycles, but then those diagrams need to "convert" into detailed documentation artifacts. This hop from slides to tools like visio and draw.io are often not taken on by the person who created the initial slide diagrams. The ability to convert these diagrams quickly would be a MASSIVE win and boost the adoption of draw.io as a differentiating feature, especially since even tools like Lucidchart can't achieve this today.

In theory, it feels like the basic boxes, lines, and images used in PPT diagrams should be fairly easy to copy/paste into draw.io if the feature can be prioritized.

**Comment by davidjgraph** [comment]
Thanks for your suggestion and interest. However, having balanced the gain against the effort of implementation and maintainance, we are declining this feature request.

**Comment by FarmDoc** [comment]
> The main disconnect for me is that lots of software architecture diagrams have humble beginnings in slide decks. They get massaged through pre-sales and discovery cycles, but then those diagrams need to "convert" into detailed documentation artifacts. This hop from slides to tools like visio and draw.io are often not taken on by the person who created the initial slide diagrams. The ability to convert these diagrams quickly would be a MASSIVE win and boost the adoption of draw.io as a differentiating feature, especially since even tools like Lucidchart can't achieve this today.
> 
> In theory, it feels like the basic boxes, lines, and images used in PPT diagrams should be fairly easy to copy/paste into draw.io if the feature can be prioritized.


I have a similar problem. We have lots of Powerpoint documents and want to use this to work in wiki.js, but in a way that allows further usage.

Also the way is not far. Powerpoint can export SVG. 
But Idid not find a way to import this in a way that can be properly edited
