### ISSUE TITLE
Update color pattern for AWS icons (DB services now pink)

### ISSUE THREAD

**Issue by typex1** [jgraph/drawio#3677]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

Just yesterday I discovered that the official color code for AWS database icons switched from blue to pink. To confirm, just go to https://docs.aws.amazon.com/index.html and then scroll down and select Product Category > Database (11). You will see the pink icons.

**Describe the solution you'd like**

I would be great to have an updated color scheme for the AWS icons also in draw.io

**Describe alternatives you've considered**

**Additional context**

**Comment by elliotsegler** [comment]
Up to date icons for q2-2023 are available here: https://d1.awsstatic.com/webteam/architecture-icons/q2-2023/Asset-Package_04282023.ca9655a386a46bda0b6238cca2651e8f27fcb5c9.zip

**Comment by hakanson** [comment]
Note that Release 16 (2023.04.28) of [AWS Architecture Icons](https://aws.amazon.com/architecture/icons/ no longer have gradients and elements are designed to appear on either white or black backgrounds for optimal contrast and visibility. Color palette updated to align with AWS branding with hex colors available on the downloadable PPT.

https://github.com/awslabs/aws-icons-for-plantuml/releases/tag/v16.0 may save some time investigating changes with https://github.com/awslabs/aws-icons-for-plantuml/blob/main/AWSSymbols.md having a visual table of icons.

```python
COLOR_VALUES = {
    "Nebula": "#C925D1",
    "Mars": "#DD344C",
    "Orbit": "#01A88D",
    "Endor": "#7AA116",
    "Cosmos": "#E7157B",
    "Smile": "#ED7100",
    "Galaxy": "#8C4FFF",
    'Squid': "#232F3E",
    "White": "#FFFFFF",
}
```

**Comment by hakanson** [comment]
@davidjgraph - I see from the README that "draw.io is closed to contributions", but is there an easy way to accelerate the adoption of new AWS icons?  Historically, updates seem to happen 3-4 times a year.  Is there a way for this to be built independently and user updated / imported?

**Comment by davidjgraph** [comment]
Not really. The issue only has one vote on it, so won't appear in any priority list.

We're SOC 2, which makes it really hard to accept external contributions, we just don't have a process to do that.

We're running late on a number of issues this year, so the focus has been paying users on the atlassian integrations, partly due to the extra workload of SOC 2...

AWS used to give us a preview of new icon sets. We used to have the new set ready on launch day. They stopped previews, makes updating come later, sometimes sets are out for weeks before we realise. The most constructive thing would be if we got previews again.

Google cloud has also deprecated virtually everything we're running on there, so there's a lot of infrastructure movement behind the scenes.

Mostly important it's August, we take not working in August very seriously here 8-) . (If you're paying confluence users, support is properly staffed there).

**Comment by image72** [comment]
download your icon sets, use this [drawio-svg-library](https://github.com/LukasPatzke/drawio-svg-library), will wrap svg file to mxlibrary file drop into drawio page, will import library and select anyone, change color on top right style panel.

reference
https://www.drawio.com/doc/faq/svg-edit-colours

**Comment by davidjgraph** [comment]
And yes, we can see when a single IP group suddenly votes for an issue. Don't do that.

**Comment by hakanson** [comment]
@image72 - thanks for that link and definitely an option to load current AWS icons.  There is likely an impact in file size, since when the `<mxCell>` has a `style="...;shape=mxgraph.aws4.resourceIcon;resIcon=mxgraph.aws4.aurora;"` it references a shape / resIcon built into to draw.io, but when using from an imported .xml based library, the `style="shape=image;image=data:image/svg+xml,XXXX...XXXX;"` includes the full base64 encoded version of the image.

@davidjgraph - I would assume not a coordinated effort on votes - just a lot of individuals finding this issue important (that maybe work at the same company).  With your SOC constraint, what do you recommend to accelerate this?  Preview access in itself might give a couple days or weeks lead time, but wouldn't help with priority or reducing effort to update.

**Comment by image72** [comment]
@hakanson 
just click Menu extras > configuration. paste below config, apply, and reload.
```json
{
  "customColorSchemes": [
    [
      {
        "fill": "none",
        "stroke": "pink"
      }
    ]
  ]
}
```

select any aws icon, and choice color stroke. 
![image](https://github.com/jgraph/drawio/assets/243154/eabf91ea-ab65-40a5-b1b7-285dcb953466)

or Maybe I misunderstood what you meant?
I'm not good at english.

**Comment by davidjgraph** [comment]
Updated in 21.7.4. Thank you @typex1 for the hint, we had missed that update.
