### ISSUE TITLE
Unnecessary blue lines appear in document during edit.

### ISSUE THREAD

**Issue by baryshainulin** [jgraph/drawio#3695]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Strange blue lines appear on edit area. The lines disappear after zooming made, then appear in a moment.
The lines do not appear on image render.
Reproduces on all diagrams of specific document only.

**To Reproduce**
1. Go to editing a diagram which contains arrows and boxes.

**Expected behavior**
No extra strange lines appear on screen.

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/17410361/fcfed9f2-7ad4-455b-8ee0-0fc91c230b57)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [21.5.1]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 64 bit
 - Version 114.0.5735.135

**Additional context**

**Comment by eensander** [comment]
It seems that I am experiencing the same problem. For me, the lines seem to be the alignment-guiding lines that appear when rearranging elements, but for some reason (sometimes) don't disappear when the rearranging stops. 

I'm using https://app.diagrams.net version 21.5.2 on Firefox for Windows (also seems to happen in Chrome). 

Minimal reproduction: 
![image](https://github.com/jgraph/drawio/assets/50321538/82b6629d-cbcc-42dd-a455-4b9fec01b747)

**Comment by mararad** [comment]
@eensander Could you please attach video showing whole browser with all the performed steps and the results?

**Comment by eensander** [comment]
@mararad When making the screenshots in my previous reply, the problem occured almost instantly. Since it took a lot more steps now, it seems my reproduction was rather unstable. Though, I was able to make a recording of the problem occuring eventually.

The video:

https://github.com/jgraph/drawio/assets/50321538/242a0da0-f77b-437a-b70f-8b0f283126c1

Notice the problem happening around 1.12. I think it happened when duplicating with ctrl+drag. However, I feel like it also sometimes happened (in practice) when regularly dragging elements.

Version: 21.5.2

**Comment by davidjgraph** [comment]
Fix in core 21.6.1 release.
