### ISSUE TITLE
 BUG：draw.io for Notion Chrome extension with chinese

### ISSUE THREAD

**Issue by Angel0726** [jgraph/drawio#3848]
### Preflight Checklist

* [ x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When editing Notion with the draw.io for Notion extension in the Chrome , there is an issue with saving if there are Chinese characters in the diagram. However, if there are no Chinese characters, the above-mentioned issue does not occur.

**To Reproduce**
1. insert draw image
2. edit drawio with chinese
3. exit edit 
4. Error popup appears。
![image](https://github.com/jgraph/drawio-desktop/assets/32816780/05736c2e-441c-473d-a8b0-09e56386f05a)

**Expected behavior**

**Screenshots**

![image](https://github.com/jgraph/drawio-desktop/assets/32816780/95232d48-1c55-425d-b462-35c9bd72fcb4)
![image](https://github.com/jgraph/drawio-desktop/assets/32816780/05736c2e-441c-473d-a8b0-09e56386f05a)

**Desktop (please complete the following information):**
 - OS: edge
 - 
**Additional context**

**Comment by alderg** [comment]
Fixed in version 1.2.5. You can force an update by clicking on Details for the plugin under Extensions, Manage Extensions:
<img width="411" alt="Screenshot 2023-09-11 at 17 45 43" src="https://github.com/jgraph/drawio/assets/921200/3d93652a-3122-4f46-a9c5-07550bcf10cd">

Then enable Developer mode and click on Update:
<img width="943" alt="267076592-3aed6858-dbf8-40d4-95de-9789415b3ea4" src="https://github.com/jgraph/drawio/assets/921200/f35c55cf-6c5c-4548-8733-310cf38d1018">

**Comment by Angel0726** [comment]
thanks
