### ISSUE TITLE
Add pages management features

### ISSUE THREAD

**Issue by mberubenet** [jgraph/drawio#4055]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
Draw.io is a great tool but it lacks pages management features for complex projects with many pages (20+). 

**Describe the solution you'd like**
This is what I would want :

- Possibility to group pages : create a group with a name and then add new or existing pages to a existing group. Maybe an icon could be shown to indicate that this tab is a group. Possibility to remove pages from group or to delete all pages of a group.
- Possibility to nest groups (add groups into another group) 
- Possibility to archive or hide pages/groups (they still in the file but don't appear in the tabs at the bottom of the page. Need to go to separate menu option to show them back)
- Possibility to select multiple pages/groups for an action (group, archive, delete, move)
- Possibility to set color to page/group tabs to find them quickly

**Describe alternatives you've considered**
As an alternative, what I do now is using page title prefix to "group" them. I "archive" the old diagrams at the end of the list. If grouping is difficult to implement, the possibility to set page tab colors (like in Excel) would be a decent alternative.

Thanks

**Comment by Peeeet** [comment]
This seems like a lot of extra layers of abstraction on top of the already existing "Layers" "Tags" and "Pages" nomenclatures, especially since a page currently can be used as a somewhat "infinite canvas" that you could layout like a wireframing / prototyping tool such as Figma.

Also you can set a "viewbox" for each link (in addition to hiding and showing tags, layers, nodes, etc) so you could create a lot of this functionality with tags and layers - panning and zooming around inside of a single page:
https://jgraph.github.io/drawio-tools/tools/link.html

I feel like between that, and the fact that you could just open drawio diagrams in different browser tabs (and then group your tabs etc) all of your use cases could be covered to a high enough degree that adding more complicated levels of organization seems out-of-scope, especially when compared to the existing functionality of other similar diagramming / graphics tools.
