### ISSUE TITLE
Text setting is exporting as svg image is missing

### ISSUE THREAD

**Issue by shanhx2000** [jgraph/drawio#4153]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

If you are technical, you should reporting bugs along the lines of https://marker.io/blog/how-to-write-bug-report. If you are not technical, we will make allowances, please try to make an effort to understand the process.

**Describe the bug**
I knew draw.io has a setting when exporting SVG image "Convert labels to SVG". However, since yesterday and today, I am not able to find that setting (follows the similar step in https://github.com/jgraph/drawio/issues/4056). 
![image](https://github.com/jgraph/drawio/assets/48196652/899a4433-b4bf-4ab0-a421-5b067db53355)

**To Reproduce**
1. Open a new diagram
2. File, export as, svg..., or File, export as, advanced, change format to svg
3. Got the image attached. 

**Expected behavior**
There is no "Text Settings" "Convert labels to SVG" in SVG export interface. Missing this function leads to words getting incorrectly wrapped after being exported as SVG images. 

**Screenshots**
![image](https://github.com/jgraph/drawio/assets/48196652/504be55e-00c9-4645-81a5-45fb74381530)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version v23.0.2

**I tested the problem in incognito/private mode with all browser extensions switched off, write "yes" below:**
- yes, firefox and chrome (not turn off extensions in chrome)

**Comment by davidjgraph** [comment]
This was removed in the v23 release. Could you please show an example output where there are problems. Includes which items you ticked in the SVG export dialog.

**Comment by saire-lancelot** [comment]
I have the same problem. Previously I was able to export the images with the setting "Convert labels to SVG" without any problems and insert them into a Word document. Then the image could also be zoomed without problems. 

Since this setting is now missing, embedded graphics and text become blurred when zooming.

Can you restore the setting as soon as possible? I am currently writing a paper and would need the SVG option. 

I have selected the following settings:

<img width="161" alt="Screenshot 2024-02-14 104357" src="https://github.com/jgraph/drawio/assets/35135500/377bbe95-fd79-4b46-924b-b967d94906c9">

**Comment by davidjgraph** [comment]
We can't, no, it requires a server element that we're no longer running. Could you please show me an example of a problem export?

**Comment by saire-lancelot** [comment]
Yes sure. 
I tick the following options in the SVG export:
<img width="237" alt="Screenshot 2024-02-14 105612" src="https://github.com/jgraph/drawio/assets/35135500/b3dd45c3-ab53-49f5-a8d1-666c4dec5209">

When I then import the SVG image into word, the text is already slightly blurred (strangely enough not for the labels, only for the text elements).

<img width="237" alt="Screenshot 2024-02-14 105612" src="https://github.com/jgraph/drawio/assets/35135500/47b53f1b-4098-4fc5-8baa-b63810cea5d8">


If I then create a PDF export, the graphics and the text are extremely blurred. Previously this worked perfectly with exactly the same settings.

<img width="316" alt="Screenshot 2024-02-14 105643" src="https://github.com/jgraph/drawio/assets/35135500/eea8f618-bcf0-48c2-aa99-e433be47129a">


I don't know how else I can embed the graphics so that they are always sharp when zooming. Even if I embed a high-resolution PNG, the PDF export is then unsharp.

Is there any other solution if you can no longer offer this? This option was never available in the desktop app, so I can't do it there either.

Many thanks for your assistance

**Comment by saire-lancelot** [comment]
Yes sure. 
I tick the following options in the SVG export:
<img width="237" alt="Screenshot 2024-02-14 105612" src="https://github.com/jgraph/drawio/assets/35135500/b3dd45c3-ab53-49f5-a8d1-666c4dec5209">

When I then import the SVG image into word, the text is already slightly blurred (strangely enough not for the labels, only for the text elements).

<img width="138" alt="Screenshot 2024-02-14 110333" src="https://github.com/jgraph/drawio/assets/35135500/4d52dea0-eb85-4cf6-af0c-9660b8997e76">



If I then create a PDF export, the graphics and the text are extremely blurred. Previously this worked perfectly with exactly the same settings.

<img width="238" alt="Screenshot 2024-02-14 110324" src="https://github.com/jgraph/drawio/assets/35135500/b4420f71-c34e-41d8-9cca-a584361cfe0c">


I don't know how else I can embed the graphics so that they are always sharp when zooming. Even if I embed a high-resolution PNG, the PDF export is then unsharp.

Is there any other solution if you can no longer offer this? This option was never available in the desktop app, so I can't do it there either.

Many thanks for your assistance

**Comment by davidjgraph** [comment]
inkscape in.pdf --pdf-poppler --export-text-to-path --export-plain-svg --export-filename out.svg

**Comment by saire-lancelot** [comment]
I have just tried that. The image remains sharp until it is exported from the Word document to a PDF document. Why exactly is this option no longer possible in draw.io? That was an awesome and simple option.

**Comment by saire-lancelot** [comment]
The text elements are now sharp but the graphics are not embedded correctly.
<img width="199" alt="Screenshot 2024-02-14 112438" src="https://github.com/jgraph/drawio/assets/35135500/972a920f-2db1-4071-a69d-f2029f088947">

**Comment by davidjgraph** [comment]
are you sure your graphics aren't just images?

**Comment by saire-lancelot** [comment]
They are 512x512 pngs but i think draw.io converted them to svg before without any problems. Definitely it worked before with exactly these settings.

**Comment by davidjgraph** [comment]
There's no conversion from PNG to SVG. If you use vector images in your diagram then this process should be good.

We used inkscape behind the scenes previously, you just need to repeat this locally.

**Comment by saire-lancelot** [comment]
This way it is now working. Many thanks for the support!

**Comment by xu-jiachen** [comment]
> This way it is now working. Many thanks for the support!

Hi Saire, could you please share how you solved it?

**Comment by alderg** [comment]
See https://github.com/jgraph/drawio/discussions/5165
