### ISSUE TITLE
Generate Custom Shapes?

### ISSUE THREAD

**Issue by FunkyLoveCow** [jgraph/drawio#434]
Is there a way to programatically import and generate custom shapes? 

I have several different shapes that I'd like to generate based on a CSV. I have length and width for each. Each shape would be a rectangle with these two values and a text field label. 

How can I generate the relevant data so that I can import these items to the scratchpad? I've found documentation on how to make flow charts from a CSV, but that's not my goal. I *just* want the custom shapes (rectangles) and if I could generate the appropriate XML and then import that I'd be happy too.

Is there documentation on how to generate shapes for import?

**Comment by GaTechThomas** [comment]
This is very much in line with what I need.

This functionality would open up quite a large set of options for draw.io. 

I'm a developer and would be interested in helping to make it happen.

**Comment by davidjgraph** [comment]
If the shapes are image based, https://github.com/jgraph/drawio-libs describes the process, is that enough?

**Comment by GaTechThomas** [comment]
Maybe so. I'll give it a try this week.

**Comment by GaTechThomas** [comment]
I gave the library option at try, but I don't think that my need is supported. I have a shape that is a container (just a 'rect') that has a few basic shapes as children. I would like to use CSV to create any number of instances of that shape. With that, also need to parameterize it, so that each child shape can have custom text and be made visible or invisible based on data in the CSV table.
