### ISSUE TITLE
Draw.io doesn't keep my settings and custom libraries

### ISSUE THREAD

**Issue by jarisgv** [jgraph/drawio#436]
Hello guys.
Draw.io is fantastic. That's why I started using it for many purposes. But I can't save my preferences to the layout of the app.
I tested the two versions, installed and portable (Draw.io 10.6.8) but every time I start the program my configuration is reset. The window always starts 4:3, the toolbar expanded and I have to import my custom libraries again.
I searched for a .ini or .xml file but found nothing in the portable root folder or in 'AppData\Roaming\draw.io'.
Is there any way to create a .xml or .ini file and setup my preferences for the application and libraries?
Thanks a lot.

Screencast showing the problem - 1m03s

[![Screencast](https://user-images.githubusercontent.com/19142770/58233283-064b6b00-7d12-11e9-862d-45b185094f7a.png)](https://youtu.be/SWnfG_LOtmg)

**Comment by davidjgraph** [comment]
Why closed? If it's the case, it's valid.

**Comment by ianclarksmith** [comment]
I was about to open new issue but stumbled on this while searching for possible solutions. In my case, I would like to be able to maintain a single configuration file and multiple custom libraries for multiple users on a shared network. Preferably, no user interaction would be required to set this up (deployed by IT for example).

Accomplishing these things are documented for users of the online app or Confluence version, for example [here](https://www.diagrams.net/doc/faq/configure-diagram-editor) and [here](https://drawio.freshdesk.com/support/solutions/articles/16000067790-work-with-custom-shape-libraries).

Possible solutions:
1. Config file to have a default location when using the desktop app.
2. Config variables, e.g. `%CustomLibraryPath%` in order to use local paths for library files. Perhaps allow this variable to be defined in the config itself.

The best alternative I have right now is diagram showing users how to add the custom configuration by opening a file, copying it to clipboard, pasting into the Draw.io desktop app, and relaunching. Then opening custom libraries one-by-one (this one could just be me needing to read the docs more closely– I haven't had success loading a library XML from a URL, but could probably encode and then inline with the config).
