### ISSUE TITLE
Some math examples don't render well

### ISSUE THREAD

**Issue by mararad** [jgraph/drawio#454]
The first math example (https://desk.draw.io/a/solutions/articles/16000032875) doesn't render well when put into shape. Others render well. Tested in Chrome and Incognito. Example copied and pasted into new draw.io editor via Ctrl+c/Ctrl+v, 
![Math](https://user-images.githubusercontent.com/44292306/59416602-fdf0c800-8dc5-11e9-9495-3d8e576659a7.PNG)

**Comment by ashrafteleb** [comment]
In the page https://desk.draw.io/a/solutions/articles/16000032875

"If the math is not converted, try clicking the </> button in the toolbar to show hidden HTML tags."

The issue is having HTML tags inside. One way to easily remove all HTML formatting, copy the label, paste to a plain text editor, then copy from that editor to draw.io
