### ISSUE TITLE
Format panel styling issues on FF on Gnome

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/drawio#465]

**Comment by eceforge** [comment]
Since the original discription doesn't provide much detail I think this is what we are talking about:
![image](https://user-images.githubusercontent.com/1264890/60402160-b34eaa00-9b40-11e9-87f3-925cce9973c8.png)
Where the right panel formatting seems odd, but only in firefox. 
It would be really nice if the width of that panel could be changed, but at least I now know that the problem is only in firefox.
