### ISSUE TITLE
搜狗输入法第一个字母直接英文

### ISSUE THREAD

**Issue by Jial08** [jgraph/drawio#4802]
不管是win10还是Linux，搜狗输入法的第一个字母都直接英文输入了，从第二个字母才开始按拼音拼写，如下输入哈哈：
[输入异常](https://gitee.com/Jial08/blog-image/raw/master/20210131150702.png)
还请修复该问题，感谢！

**Comment by grey6966** [comment]
我也是遇到这个问题，好像是最近才有的， 大家看一下有什么共性原因没有？ 大家装过  类似 capslock 等软件吗 ？ 

好久能解决呀，我都想重装系统了

**Comment by Ryan-Wo** [comment]
不只是自带输入法，全部输入法都这样！烦死了，后面的字删除还会调到第一个字母

**Comment by davidjgraph** [comment]
There are two types of editing. 1) input when text editing is live on a shape and 2) input when a shape is selected, not editing is not yet live.

In the first case, that is if you edit by double clicking a shape or pressing enter on a selected shape, the text editor shows and a CJK input (there may be other language) inputs the first character correctly. This is because the text editing is live and we don't have to process anything. The OS IME deals with everything for us.

In the other case, perform text input to a selected cell, we have to capture the event, start the text editing and send the input the the text edit. The problem here is there isn't a way to insert that input back into the OS IME, so we get the input wrong for the first character in certain character sets that require the OS IME to handle them.

We do not have a workaround to the second case. When using CJK, just ensure you always start editing by pressing enter on a selected shape, or double click it.

Chinese:

有两种编辑方式：
1）在形状上实时进行文本编辑；
2）在选中形状时尚未进入实时编辑状态。

第一种情况是，当你通过双击形状或在选中形状后按 Enter 键进入编辑模式时，文本编辑器会显示，此时 CJK 输入法（以及其他某些语言输入法）能够正确输入第一个字符。这是因为文本编辑处于实时状态，我们无需额外处理，操作系统的输入法编辑器（IME）会自动处理所有输入。

第二种情况是，在选中形状后直接输入文本。此时我们需要捕获输入事件，启动文本编辑器，并将输入内容传递给编辑器。问题在于，我们无法将该输入事件重新交回操作系统的输入法编辑器（IME）处理，因此对于某些需要操作系统 IME 处理的字符集，第一个字符的输入会出错。

针对第二种情况，目前我们没有可行的解决方案。使用 CJK 字符时，请务必通过在选中形状后按 Enter 键或双击形状来开始编辑。


Japanese:

編集には2つの種類があります。
1）図形上で直接テキストをリアルタイム編集する場合。
2）図形を選択しているが、まだリアルタイム編集状態に入っていない場合。

1つ目のケースでは、図形をダブルクリックするか、選択した図形で Enter キーを押して編集を開始すると、テキストエディタが表示されます。このとき、CJK（日本語・中国語・韓国語など）の入力方式（およびその他の言語入力方式）では、最初の文字が正しく入力されます。これは、テキスト編集がリアルタイムで行われ、OS の IME（入力方式エディタ）がすべてを処理するためです。

2つ目のケースでは、図形を選択した状態で直接文字を入力すると、アプリ側で入力イベントを捕捉し、テキストエディタを起動して入力内容を渡す必要があります。しかし、この入力を再び OS の IME に戻す方法がないため、IME に依存する一部の文字セットでは、最初の文字が正しく入力されない問題が発生します。

この2つ目のケースについては、現時点では回避策がありません。CJK 文字を使用する場合は、必ず図形を選択して Enter キーを押すか、ダブルクリックして編集を開始してください。


Korean:

편집에는 두 가지 유형이 있습니다.

도형 위에서 직접 실시간으로 텍스트를 편집하는 경우,

도형이 선택되어 있지만 아직 실시간 편집 상태로 들어가지 않은 경우입니다.

첫 번째 경우, 도형을 더블클릭하거나 선택된 도형에서 Enter 키를 눌러 편집을 시작하면 텍스트 편집기가 표시됩니다. 이때 CJK(중국어, 일본어, 한국어 등) 입력 방식(및 기타 일부 언어 입력 방식)에서는 첫 글자가 올바르게 입력됩니다. 이는 편집이 실시간으로 이루어지고, 운영체제의 IME(입력기)가 모든 처리를 담당하기 때문입니다.

두 번째 경우, 도형을 선택한 상태에서 바로 텍스트를 입력하면 애플리케이션이 입력 이벤트를 감지하고, 텍스트 편집기를 실행하여 입력 내용을 전달해야 합니다. 그러나 이 입력을 다시 운영체제의 IME로 되돌릴 방법이 없기 때문에, IME 처리가 필요한 일부 문자 집합에서는 첫 글자가 잘못 입력되는 문제가 발생합니다.

두 번째 경우에 대해서는 현재 우회 방법이 없습니다. CJK 문자를 사용할 때는 반드시 도형을 선택한 후 Enter 키를 누르거나 도형을 더블클릭하여 편집을 시작하십시오.

**Comment by Haohao-end** [comment]
输入法的bug 在其他地方也有这个问题

**Comment by davidjgraph** [comment]
Fix in 29.5.3
