### ISSUE TITLE
Add ability to use Google fonts

### ISSUE THREAD

**Issue by AndreasHae** [jgraph/drawio#577]
Please add the ability to use fonts directly from fonts.google.com, without having to install them first.

**Why?**
To achieve a consistent look, I want my diagrams to match the font of my documents. As I'm using Google Docs, I naturally want to use fonts from Google, like Roboto or Open Sans. These are unfortunately not available by default. You _can_ install them locally and use them via the "Custom font" option, but that is rather cumbersome and has the disadvantage that the fonts will differ when sharing the drawing.

**Comment by CoolZeroNL** [comment]
You can use a plugin to load all the google fonts, so that the google fonts are always installed on load of draw io.

I have added to the custom fonts "Roboto", "Open Sans" & "Libre Franklin". But you can add/change this setting if you want. (you need to fork oid the repo)

Because now all the fonts are installed, you can add custom fonts in Draw.io by entering the name of the font family. 

Draw.io Plugin URL:
https://yacdn.org/serve/https://raw.githubusercontent.com/CoolZeroNL/draw-io-plugins/master/%23%20Draw-io-plugin-Google-Fonts/google-fonts-v1.js?maxAge=10

**Comment by alderg** [comment]
You can now use the built-in Font picker:
![google-fonts](https://user-images.githubusercontent.com/921200/69730318-1ceed680-1128-11ea-8ec7-6d921914a85e.gif)
