### ISSUE TITLE
"Snap to Grid" mode.

### ISSUE THREAD

**Issue by RobertZenz** [jgraph/drawio#613]
It would be nice if there was a "Snap to Grid" mode which can be activated as needed, so that any movement/resizing of shapes would *always* snap to the grid. So shapes can only be moved and resized according to the grid size.

If one is using the grid for outlining components, such a mode would be quite helpful as it would directly position the components at the appropriate locations without having to it manually. Ideally this would be a toggle under the "View" or "Arrange" menu.

**Comment by 28raining** [comment]
+1

**Comment by acfrery** [comment]
I concur with this request. "Snap to grid" should be an option.

**Comment by davidjgraph** [comment]
Please thumbs up the original post to vote for it.

**Comment by JeffJuliano** [comment]
I find it difficult to align arrows where I want them because of lack of snap-to-grid feature.
I couldn't find a good workaround either?

**Comment by yadd** [comment]
"Snap to grid" would be a super feature. Without it, shapes (like boxes) which I intend to be aligned vertically or horizontally end up fractionally out of line. This has knock-on effects on connector positioning since (for example) connection points that should be directly opposite each other are not quite directly opposite, and the line is therefore not straight.

There is a workaround, which is to use the Arrange -> Position entry box to ensure the alignment of a shape to the grid, and the use "Align Top" / "Align Left" / whatever to ensure that other shapes are aligned to the first. But this is rather tedious, particularly when there are a lot of items on a drawing and one is trying different arrangements in order to increase clarity. A "Snap to grid" feature would be a great way of making life easier in this regard.

**Comment by alderg** [comment]
If the grid is visible snap to grid is always enabled.

**Comment by davidjgraph** [comment]
Now that snapping is enabled while the grid is on and there's a manual snap to grid function, I'll going to close this issue. I think there are addition issues around snap to grid, but I'd prefer to go into specific examples in new issues, rather than leaving the generic case open.

**Comment by guyhoulsby** [comment]
Snap to grid simply does not seem to work. It is a confusing function which seems to behave in a random way.

**Comment by Tbohunek** [comment]
> Now that snapping is enabled while the grid is on and there's a manual snap to grid function, I'll going to close this issue. I think there are addition issues around snap to grid, but I'd prefer to go into specific examples in new issues, rather than leaving the generic case open.

All he above posts helped me find the one that's been bothering me: `guides` is now disabled. :)
Perhaps some minor [LEAN](https://en.wikipedia.org/wiki/Lean_project_management) adjustments could be made? Give documentation in place through "hints" @davidjgraph?

![image](https://user-images.githubusercontent.com/16520646/209806880-7d8f610f-51d0-4440-813b-7b00ff04be81.png)
