### ISSUE TITLE
[Feature request] Big ask. VUE from Tufts looks mothballed. Drawio is perfect!

### ISSUE THREAD

**Issue by joel-marks** [jgraph/drawio#682]
[VUE (Visual Understanding Environment)](http://vue.tufts.edu/index.cfm) is (was) the very best tool I ever found for rapidly prototyping concepts and ideas. It had some very intriguing non-linear presentation modes as well. There is nothing out there like it that I have found. Even Drawio is not as good for rapidly putting together ideas. 

VUE from Tufts University appears mothballed (last updated in 2015,). It doesn't work with modern Java, and Apple have made the old version of Java obsolete, making it hard (although not yet impossible) to install. VUE is now nearly broken on MacOS with unresolved bugs and UX issues due to lack of maintenance.

Things that made VUE so good for rapid use:

- Uncluttered UX
- Page cannot scroll beyond edge of drawing, so you cannot accidentally scroll away
- Items can be nested, so no need to create a special 'list' object because any object could store a selection of other objects
- Items (even when nested) are easier the Drawio to draw lines between because of a difference in UX. Drawio allows arrows to attach to more bounding points on an object but this creates additional UX complexity
- Keyboard shortcuts like (r=rapidadd and s=select) were perfect in VUE for rapid use

**I wonder if the kind souls at Drawio would consider looking at what made VUE such a good program and implement some of its features???**

**Comment by davidjgraph** [comment]
Thanks for the issue, however, it's rather too broad in scope to be something we'd want to do. Plus it's fundementally changing something that 10s of millions of users use for 1 users. If you wanted to go down this route, forking the project and implementing is the better way to go.

**Comment by pplatek** [comment]
I wanted to just add a +1 for this issue (so you'll have 2 users vs 10s of millions ;-)) when I started writing this, because I too found VUE's way of creating concept maps easier than drawio's.  I haven't been able to put my finger on the reasons.  In below's attempt, I realized that drawio just has different ways of doing similar tasks, so below became a VUE to drawio guide instead haha:

> Uncluttered UX

Can you elaborate on this one?  To me it seems that drawio is actually ok.

>  Page cannot scroll beyond edge of drawing, so you cannot accidentally scroll away

I haven't really experienced this in drawio, but we can use "Home" key or "Find" to locate some concept on the map and move the view to it?

> Items (even when nested) are easier the Drawio to draw lines between because of a difference in 
UX. 

Yeah, this might be where VUE wins.  In VUE you can hit 'r' (Rapid Prototyping) on the keyboard and click-drag between nodes to connect them, and in addition, VUE will automatically put you in edit mode for that edge, so you can just type your linking phrase right away instead of looking for the edge you just created.  
However having said that, in drawio, you can just use "Alt-Shift+Arrow" to clone current node and create an edge, type in your Concept, "Shift-Tab" 2x and you can create/update the "linking phrase" on the edge.  I wish this was 1 "Shift-Tab" since they're visually next to each other, but oh well.

> Drawio allows arrows to attach to more bounding points on an object but this creates additional UX complexity

This can be solved by holding "Shift" when creating the edge using drawio's 4 different ways to connect shapes? https://drawio-app.com/4-ways-to-connect-shapes/
 
> Keyboard shortcuts like (r=rapidadd and s=select) were perfect in VUE for rapid use 

Drawio is pretty much in VUE's r (Rapid Prototyping) mode for Nodes already, all you have to do is use the "Clone and connect" keyboard shortcut or click the connector arrow to clone the node and  start typing.  I think in this case drawio is just as good as VUE.
However unlike VUE you can't simply click anywhere on the canvas to add disconnected nodes, you have to click on the shape you want to add or duplicate existing shapes.  I think that's fine, just different from VUE, linking concepts however... read on below.

One fundamental difference I noticed is that drawio, unlike VUE and other concept map software like CmapTools, can't support creating edges from "linking words", which in drawio are text labels on an edge, to multiple nodes.  In order to do that you, have to convert the edge text label to a text object which then gives you a node, which then allows you to have multiple edges linking to/from it.  That's quite a lot of clicking to get that done.  I'm basing this observation on following this guide: https://cmap.ihmc.us/docs/constructingaconceptmap.php.  It's currently very clunky to follow this guide in drawio.

Also VUE by default uses straight connectors for waypoints, but that's easy to modify by selecting your preferred style and it'll become the default for that diagram.

> It had some very intriguing non-linear presentation modes as well

I haven't really had a chance to use this, and yes I saw the videos and it seems pretty cool, but embedding images in VUE was always kind of clunky, so I never bothered actually using the presentation mode.  Perhaps this is worth investigating more, because drawio is much better at inserting different media so adding a presentation mode would make it even better.

Also for creating concept maps, if you want to follow the parking lot first style as suggested in https://cmap.ihmc.us/docs/constructingaconceptmap.php, it is a bit awkward to create a bunch of nodes first that are at first disconnected yet spaced from each other

VUE also Auto resizes nodes to entered text once you click outside of it, in drawio, finish typing, Esc, then Ctrl-Shift-Y (extra shortcut to remember, it would be nice to have an option for auto resize)
 
VUE also has a Ctrl-R (reselect) shortcut which would be nice in drawio

This is just a few things I noticed when trying to migrate over from VUE to drawio.  Hopefully this will help someone else coming from VUE or other concept mapping software.
