### ISSUE TITLE
[Feature Request] CSV import: connection label reference to a field

### ISSUE THREAD

**Issue by Merisho** [jgraph/drawio#690]
So we have the ability to add any label we want to a particular shape by specifying the following in CSV import: `# label: %name%`

But seems like there is no way to specify a connection label like that: `# connect: {"from":"refs", "to":"id", "label": %name%}` puts the string "%name%" as a label of all connections, instead I want it to refer the `name` column of the given CSV

**Comment by awing2x** [comment]
+1 one for this feature.
Is there any known workarounds for this?

**Comment by jbperrin88** [comment]
You can use fromlabel and tolabel column

**Comment by nickmel-uc** [comment]
+ 1 for this feature.  @jbperrin88 can you expand on the`fromlabel` `tolabel` solution?  I can't seem to find documentation for that.

**Comment by bojika** [comment]
+1 one for this feature.
Is there any known workarounds for this?

**Comment by davidjgraph** [comment]
There is no currently known workaround, but we haven't investigated in depth.

**Comment by souliane** [comment]
Hello,

I am trying to write something to convert structurizr DSL JSON [1] to the diagrams.net CSV format, but I am facing the same problem as @Merisho.

Since C4 objects are already in diagrams.net, I would like to import similar objects to what we can manually do with the C4 objects:
![image](https://user-images.githubusercontent.com/21343492/146801535-eaf9615b-4720-4b1e-aaba-e5a829dee442.png)

I think the connectors should be defined in the "normal" CSV content, not in comments. One mandatory CSV column could serve to tell "this is a box or a connector". Then we can use a "comment" similarly to what is currently done to tell "use this connector from this box to that one", but it should be possible to attach properties to the connectors, just like we can do for boxes.

Alternatively, is there maybe another mechanism to programmatically transfer data from another format to something diagrams.net can read:

1. beside the CSV or text importer
2. without having to dive deep in diagrams.net source code
3. without having to deal with positioning of the elements
?

Thanks
[1] https://github.com/structurizr/dsl

**Comment by EdgarSchouten** [comment]
If the data provides a column named (for example) `relationLabel` then you will be able to create a connector between nodes with a label taken from data in that named column, by using the `fromlabel` property in `# connect` referencing that column.
```
# connect: {"from": "relatedTo",  \
  "to": "id", \
  "fromlabel": "relationLabel", \
  "invert": false, \
  "style": "curved=1" \
}
```

```
## CSV below this line. First line contains comma-separated column names
id,name,relatedTo,relationLabel
car,Car,person,drives
person,Person,car,drivenBy
```
