### ISSUE TITLE
Add support for rich-text notes

### ISSUE THREAD

**Issue by jpragma** [jgraph/drawio#711]
It would be extremely useful to have an additional tab in "Format Panel" that could be used to add an arbitrary note to the currently selected element. Supporting rich-text in these notes would be even better.

**Comment by gcaggia** [comment]
Support for markdown would be highly appreciated. 
Markdown with syntax highlighting for specific language.
Something like:

```php 
 echo $a;
```
I am ready to help. Is it difficult to submit a PR for such feature?

Thank you.

**Comment by maturz** [comment]
This would be great, shouldn't be a lot of work to just add a text field to the base model. It would be good though if there was a small visible icon on all items with a note in the diagram so you can easily see that they exists. Also this icon could be used to show the note on a mouseover popup.

**Comment by jpragma** [comment]
Bump up

**Comment by Kryptortio** [comment]
If this gets added it would be nice if there was a small visible icon (maybe with an option to disable it when it's not needed) on all items with a note in the diagram so you can easily see that they exists. Also this icon could be used to show the note on a mouseover popup.

**Comment by loligans** [comment]
This feature would be so nice. I really like the comment's section in LucidChart, so if something similar existed for drawio, I would be thrilled

**Comment by davidjgraph** [comment]
Commenting does exist, this feature is specific to add formating to the existing tooltip functionality.

**Comment by Kryptortio** [comment]
Unless I'm missing something commenting does not exist without Gdrive or Confluence. So for everyone not using those this could help as an alternative to comments as well but a "note overview section" might not be in scope here. 

Could be something you would want to take into consideration for the datamodel of notes though if you want to leave the possibility open for that feature and/or a comment feature that does not rely on an external service.

**Comment by davidjgraph** [comment]
Commenting requires a login for some concept of which user is commenting. What I'm not understanding is what the difference between the existing tooltip functionality (which supports HTML) and this notes concept is.

**Comment by Kryptortio** [comment]
I can only speak for myself but I think the original idea had nothing to do with tooltips (but the tooltip feature could be one way to accomplish the goal). If you wanted to reformulate this idea with the goal of solving it using the tooltip feature, I would put it like this:

1. [Show the tooltip as a separate tab in the format panel](https://github.com/jgraph/drawio/issues/711#issue-550841752) (makes it a more prominent feature and easier/quicker to access)
2. [Implement a (rich/WYSIWYG) text editor for the tooltip text](https://github.com/jgraph/drawio/issues/711#issue-550841752) (HTML is not easy for many to use but it's great that HTML works), [markdown could be an option to support as well](https://github.com/jgraph/drawio/issues/711#issuecomment-579026284)
3. [When a tooltip exists display a small icon (optionally?) so that it's easy to see that the tooltip exists without having to mouse over every item in the diagram.](https://github.com/jgraph/drawio/issues/711#issuecomment-1021977945)

Personally I would be happy with just 3 but some editing (2) options would be nice since writing HTML is slower (and not something most people can do, related #2624). I believe 1 would be good for the product though because I've used draw.io a lot and I did not know about the tootip feature (seems like it's a bit hidden now in the edit menu, looks like it might have been removed from the right click menu at some point).

In regards to comments, I don't think login is strictly a requirement (but a good feature). When login is not available comments can still be useful (and adding a signature manually is an easy workaround). Again tooltip could serve as a solution/workaround for this except for the [overview part that was mentioned.](https://github.com/jgraph/drawio/issues/711#issuecomment-1079770469)

**Comment by ironlion37** [comment]
Yes, this is a much needed feature! I've played around with the tooltips and it's a no go. Need to be able to paste rich text directly into a side panel and have an icon indicating the presence of note content on the corresponding shape in the diagram. Coming from Mindjet's Mindmanager, this was an essential feature that I used all the time. The main reason rich text is needed is for quickly pasting web page content and not losing the links.

Here's a screenshot
![Screen Shot 2022-06-06 at 9 46 48 AM](https://user-images.githubusercontent.com/106928525/172411141-9c0b08e4-effe-4941-a19b-af0c9a513ddc.png)

Another great shortcut in MindManager is ctrl+k for adding a link to shape/topic. That also adds a little chain link icon on the topic/shape.

**Comment by davidjgraph** [comment]
It's never just this or these features is the problem. To build a specific mind mapping tool would need a dedicated engineer, ultimately. It comes down to I don't want to pay out my money to fund that engineer for something I don't see any commercial return for.

**Comment by woodz-** [comment]
I suppose having a text box on a spreadsheet and enabling markdown for it, is all what we need.

A markdown engine should take care of syntax highlighting by its own, being able to recognize the while editing.

There could be ready made dev packages for different languages, I haven't checked.

**Comment by delcroip** [comment]
I would really love that, I am using drawio to create decision tree (xml parsed with python) and richtext could really streamline the edition process by  either
* clicking on the contextual menu "Edit Rich text" (a bit like edit link) that would show a modal box
* on the panel, having the rich text 

I seems that there is richtext lib such as https://quilljs.com/playground/

**Comment by davidjgraph** [comment]
Thanks for your suggestion of a feature request. Having reviewed the likely methods to implement it we've decided that the effort to implement it is excessive for the benefit. We do not want the added maintenance and security review of an external library to implement the functionality.

**Comment by dzylikecode** [comment]
> Support for markdown would also be highly appreciated.
> 
> Markdown with syntax highlighting for specific language.
> 
> Something like:
> 
> ```
>  ` ` `php 
> 
>  echo $a;
> 
>  ` ` ` 
> ```
> 
> will output:
> 
> ```
>  echo $a;
> ```
> 
> I am ready to help. Is it difficult to submit a PR for such feature?
> 
> Thank you.

I have already developed a plugin to support it. Here is the code: https://github.com/dzylikecode/drawio-plugin-markdown. But I have encountered some issues, such as the inability to highlight code for the VSCode plugin. Could you please help me? Thank you very much!

**Comment by mohamedelkony** [comment]
I hope one day
