### ISSUE TITLE
Distribute with uniform gaps between objects

### ISSUE THREAD

**Issue by chrisemb** [jgraph/drawio#736]
It would be great to have an option to distribute objects with equal distance.

Currently Arrange->Distribute->Horizontal (or Vertical) always arranges the objects in a way that their centers are of equal distance.

The desired feature is known from Inkscape (http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Align.html) and LibreOffice draw (https://help.libreoffice.org/6.2/en-US/text/shared/01/05360000.html) which both offer several options for distribution: left/top, right/bottom, center (the one also available in draw.io), spacing/gaps (the one desired as an option).

The desired feature is also known from Microsoft Office (https://support.office.com/en-us/article/Align-or-arrange-objects-bfd91078-2078-4b35-8672-f6270690b3b8) where it is the only way to distribute objects.

**Comment by bjohas** [comment]
Would love to have this.

**Comment by davidjgraph** [comment]
Please thumbs up the original post, rather than writing "me too", or "+1"

**Comment by mararad** [comment]
https://trello.com/c/Pm7Ta7GE/176-distribute-spacing-instead-of-position

draw.io has a "Distribute" command available under Arrange menu when multiple elements are selected.
Unfortunately, it can only evenly distribute the position of elements, which means elements with different sizes may have different spacing between them. It looks somewhat awkward.

I hope there can be another option where instead of position, the spacing are evenly distributed.

**Comment by alderg** [comment]
This will be added in the next release.

**Comment by davidjgraph** [comment]
Internal release https://drawio.atlassian.net/projects/DS/versions/11221
