### ISSUE TITLE
Export PDF border on the right side and bottom is wrong

### ISSUE THREAD

**Issue by jenshabermann** [jgraph/drawio#740]
First of all let me tell how much I love this tool. It is awesome to create PDFs online and with such flexibility.

The issue I have is when using File -> Export -> Advanced you can set a Border or padding. If I set this value the border will be correctly applied to the left and upper side but unfortunately the right and lower site are getting cut off.

Obviously the border is not correctly calculated. Should be easy to fix.

Thank you.

**Comment by ashrafteleb** [comment]
I cannot reproduce. Can you please attach a sample

I tried the following file and the results looks good (20 pixels border)
[borders.pdf](https://github.com/jgraph/drawio/files/4284361/borders.pdf)
[borders.txt](https://github.com/jgraph/drawio/files/4284364/borders.txt)

**Comment by preston-mccormick** [comment]
I've run into the same problem, but only in the desktop version.

**Comment by preston-mccormick** [comment]
I tried to create a sample, but could not reproduce it with a new diagram and the problem seems to go away after restarting the desktop app.  But I have definitely had issues with the bottom and right borders being smaller or missing when exporting PNGs in the desktop version.

I did find a couple of exports that suffered from the bug.  One has no border and the other has a smaller border on the bottom and right.  I generally set the border to 10px.

![form-flow-combined-3](https://user-images.githubusercontent.com/10375540/102256659-e158b300-3ec8-11eb-9009-2c4d45548c2d.png)

![form-flow-combined](https://user-images.githubusercontent.com/10375540/102256423-a0f93500-3ec8-11eb-9293-ff44afbf679d.png)
with PNG exports in the desktop version.
