### ISSUE TITLE
[Feature Request Bounty : $100] Show Search Results

### ISSUE THREAD

**Issue by fusillijerry89** [jgraph/drawio#743]
When you search, have a drop down search result where you can click on a result, and then the window moves the the x,y coords of the result you clicked on.

Similar to Miro. 

https://imgur.com/a/83qu8kS

**Comment by fusillijerry89** [comment]
Current Bounty: $100 USD

**Comment by davidjgraph** [comment]
In terms of a bountry, you're welcome to offer one, but I must clarify some issues regarding PRs in general.

This is a commercial grade piece of software. Additions to it must be of quality level of that expected from an experience, professional software engineer, properly written and properly tested. If it involves the addition of something to the UI, it must describe the possible attack vector to that addition, as well as reasonable proof any attacks have been mitigated. Also, the maintenance load of the additional code (which always exceeds the initial effort to write it) will have to be borne by the core team. We have no contractual way to force an author to maintain their work, so it must be a feature that we want added and we're happy with the way it was added.

The reason for this is people had a tendenacy to submit PRs that were poor quality. When we took them in we often spent more time fixing and refactoring then it would be been to do ourselves. And then we've a feature that's been introduced not a time we wanted it.

Please both the thread and author and anyone considering the issue think about this. Just because someone implements a PR doesn't mean we'll take it.
