### ISSUE TITLE
Commit Gitlab  file size limit

### ISSUE THREAD

**Issue by jbperrin88** [jgraph/drawio#816]
### Preflight Checklist
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Make a big diagram and save it to gitlab
In this diagram i've a lot of shape with base64 image

**To Reproduce**
1. Go to File
2. Click on Save
3. Click on Commit wirh a message

Error saving file
Drawing is too large (985.7 kB / 1 MB)

**Expected behavior**
No limit in size for this kind of save.

**Screenshots**
![image](https://user-images.githubusercontent.com/11284940/76962511-a61c5a00-691f-11ea-83cd-5392ab795ef9.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [e.g. 12.8.5] (SELF-HOSTED docker)

**Desktop:**
 - OS: windows
 - Browser : firefox 
 - Version : 73.0.1

**Additional context**

**Comment by jbperrin88** [comment]
OK ... SO i've succesfully change this limitation

This limitation comes from GitLabClient.js  line 561
-> 	if (data.length >= this.maxFileSize)

But from my point of wiew there is no reason for this .

The variable maxFileSize is an extend from GitHubClient.js

I haven't seen any where this kind of limitation in both Git .

Best Regards

**Comment by lamoquette** [comment]
Hey @jbperrin88 , 

I was looking for a solution and I found your post.
Actually I did it through my DockerFile to apply the edit, but it doesn't seem to work, and still display the error when I try to commit the diagramm on gitlab.

I tried the followed Dockerfile, could you have a look ?

```
FROM dockerproxy-iva.si.francetelecom.fr/jgraph/drawio:12.9.6-alpine

LABEL name="drawio-image"

# Give writable permission
RUN chmod a+rwx $CATALINA_HOME/webapps/draw

# Copy modified files to deactivate cloud storage and git size limitation
COPY PreConfig.js $CATALINA_HOME/webapps/draw/js/PreConfig.js
COPY GitHubClient.js $CATALINA_HOME/webapps/draw/js/diagramly/GitHubClient.js

WORKDIR $CATALINA_HOME

EXPOSE 8080 8443

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["catalina.sh", "run"]

HEALTHCHECK NONE
USER 1001
```

In my GitHubClient.js :

`GitHubClient.prototype.maxFileSize = 10000000 /*10MB*/;`

in a nutshell : 

Copy my own PreConfig.js though the dockerfile works
But not the GitHubClient.js

**Comment by quintesNZ** [comment]
Hello

Happened for me today as well, 
Drawing is too large (1016 kB / 1 MB) was the error somewhere.

I've had to resort to device / local saves.

**Comment by DannyL9143** [comment]
I was able to hack a fix, but I think this should be investigated further. The reason why it does not work when you change GitLabClient.js is because the code overall is minified and needs to change app.min.js. So you either need to regenerate app.min.js after editing GitLabClient.js OR in my case I just edited app.min.js. I found the GitLabClient line to add it to, and then append it to the end of the line.  My example is below. 

The real fix should be perhaps to consider making maxFileSize configurable for each of the file modes or, as jbperrin88 pointed out, perhaps we do not need a maxFileSize variable for GitLab at all. In our case, we are managing the magnitude of the file size with Git LFS in our repository rather than needing Draw.io to manage it for us.

My example is on line 10026 of app.min.js for my particular version of this example (see the end of the line for my part to set maxFileSize):

`GitLabFile.prototype.getMode=function(){return App.MODE_GITLAB};GitLabFile.prototype.getDescriptorEtag=function(a){return a.last_commit_id};GitLabFile.prototype.setDescriptorEtag=function(a,e){a.last_commit_id=e};GitLabLibrary=function(a,e,c){GitLabFile.call(this,a,e,c)};mxUtils.extend(GitLabLibrary,GitLabFile);GitLabLibrary.prototype.doSave=function(a,e,c){this.saveFile(a,!1,e,c)};GitLabLibrary.prototype.open=function(){};GitLabClient=function(a){GitHubClient.call(this,a,"gitlabauth")};mxUtils.extend(GitLabClient,GitHubClient);GitLabClient.prototype.clientId=DRAWIO_GITLAB_ID;GitLabClient.prototype.scope="api%20read_repository%20write_repository";GitLabClient.prototype.baseUrl=DRAWIO_GITLAB_URL+"/api/v4";GitLabClient.prototype.authToken="Bearer";GitLabClient.prototype.maxFileSize=1E8;`

**Comment by DaveRuijter** [comment]
I'm experiencing the same issue with GitHub saves.

**Comment by davidjgraph** [comment]
Increased to 10MB for next build.

**Comment by davidjgraph** [comment]
Deployed in 13.6.0

**Comment by NebzHB** [comment]
Dear, possible to extend it for GitHubClient too ?

**Comment by davidjgraph** [comment]
Please file a new issue for new requests.

**Comment by indrex** [comment]
I am on v14.6 but I still see the same issue - 1 MB limit
![CopyQ URwKEh](https://user-images.githubusercontent.com/38977850/115035096-d3a05200-9ee9-11eb-83dc-09ad345dbbe3.png)

**Comment by davidjgraph** [comment]
@indrex what URL are you using? That message is 10MB in the code since 13.6. Are you sure you are saving to Gitlab?

**Comment by indrex** [comment]
Sorry, my bad, I was committing to a GitHub repo not to GitLab :(
