### ISSUE TITLE
PDF export broke

### ISSUE THREAD

**Issue by sebschmi** [jgraph/drawio#866]
I noticed yesterday, that the PDF-export feature broke. There are two problems:

1. If I select a part of a diagram, and then export selection only and with cropping and "include a copy of my diagram", the cropping does not work correctly. I get exactly the elements I selected, but the on the left and bottom of the resulting PDF there is some unexplainable whitespace.
2. Using "mathematical typesetting" the font seems to have changed. The new one does not fit with LaTeX standards anymore, and looks weirdly bold.

**Comment by qhanson** [comment]
Same problem. Mathematical typesetting results in bold texts. Does anyone fix this? @davidjgraph

**Comment by DavidNepozitek** [comment]
I believe that the bolder font in PDF is caused by the configuration of MathJax SVG `blacker: 1`. When set to 1, the conversion to PDF is weird. My proposal is to set this option to 0 or choose different type of MathJax output.

You can see the same issue with MathJax [here]( https://www.princexml.com/forum/topic/4116/svg-output-differs-between-browser-and-prince)

**Comment by ashrafteleb** [comment]
Is this still an issue?

I tried both cropping and math and both look similar to on-screen
