### ISSUE TITLE
Custom link tool generated code does not work with multiple tags, only single tags

### ISSUE THREAD

**Issue by SanjayVyas** [jgraph/drawio#885]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Custom Link tool does not work when selecting multiple tags. However, it works correctly if multiple layer ids are used.

**To Reproduce**
1. Create two layers
2. GIve them tags L1 and L2
3. Use "Create Custom Link" tool
4. Generate "Hide" Action with tags "L1 L2"
5. Paste generated action in a button --> Edit Link
data:action/json,{"actions":[{"hide":{"tags":["L1","L2"]}}]}
6. Click the button action
BUG: It does not hide any layers
7. Replace the action with
data:action/json,{"actions":[{"hide":{"tags":["L1"]}}]}
or
data:action/json,{"actions":[{"hide":{"tags":["L2"]}}]}
and it will hide single layer

**Expected behavior**
When multiple tags are given in the custom links, all of them should be hidden

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io desktop version [e.g. 13.0.1]

**Desktop (please complete the following information):**
 - OS: [macOS 10.15.4]
 - Browser [Chrome]
 - Version [Version 81.0.4044.122 (Official Build) (64-bit)]

**Comment by Hicsy** [comment]
Sorry if this necros.
In-case anyone else comes across this issue - it's **By Design** - OP's link will *only* toggle elements with BOTH `L1` _and_ `L2` tags...

I can't find the official FAQ on-the-spot but here is a word-for-word copy of it:
https://desk.draw.io/support/solutions/articles/16000080137

> If multiple tags are used, then the cells that have all tags are selected (AND). 
   To toggle cells with either tag1 or tag2, use multiple toggle actions instead. 

cheers 🍻
